using System.Collections.Generic;
using NeptuneEvo.BattlePass.Models;
using NeptuneEvo.Chars.Models;

namespace NeptuneEvo.BattlePass.Season2Models
{
    public static class Repository
    {
               
        public static readonly List<BattlePassTask> BattlePassTask = new List<BattlePassTask>
        {
	        new BattlePassTask(0, "Принять участие в Gun Game", 1, 90, "Пойдем выйдем", "Необычное задание", 777, BattlePassRewardDiff.Medium),
			new BattlePassTask(1, "Купить модификацию на оружие в Gun Shop", 1, 30, "Кастомизация оружия", "Лёгкое задание", 500, BattlePassRewardDiff.Easy),
			new BattlePassTask(2, "Проехать 5 миль с пассажиром, будучи таксистом", 5, 90, "Таксист Младший", "Необычное задание", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(3, "Сыграть в сапера (F9)", 1, 30, "Bomb has been defused", "Необычное задание", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(4, "Cыграть на игровых автоматах в казино", 1, 30, "Три топора", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(5, "Пополнить банковский счет на 10$ через банкомат", 1, 30, "Деньжата", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(6, "Купить лотерейный билет в 24/7", 1, 30, "Везунчик?", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(7, "Реанимировать человека с помощью аптечки", 1, 30, "I need a medic!", "Сложное задание", 350, BattlePassRewardDiff.Hard),
			new BattlePassTask(8, "Купить любую одежду в Clothes Shop", 1, 30, "Модный приговор", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(14, "Передать кому-нибудь деньги", 1, 30, "Маме деньги неси!", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(15, "Купить таблетку у врача в EMS", 1, 30, "Врача!!!", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(18, "Сделать татуировку на любой части тела", 1, 30, "Кольщик, наколи мне...", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(19, "Заправить 20 литров топлива на АЗС", 1, 30, "В бак мне залей", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(20, "Отвезти 10 посылок, работая почтальоном", 10, 90, "Вам почта!", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(21, "Проехать 80 меток, работая газонокосильщиком", 80, 90, "Гонщик нелегальный", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(22, "Починить 40 электроблоков, работая электриком", 40, 90, "Фиксик", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(23, "Запустить фейерверк", 1, 30, "Моё искусство - это взрыв!", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(24, "Приехать на вызов, работая механиком", 1, 30, "Педаль в пол", "Необычное задание", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(26, "Арендовать любой транспорт", 1, 30, "Каршеринг", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(27, "Помыть транспорт в автомойке", 1, 30, "Мойдодыр", "Лёгкое задание", 666, BattlePassRewardDiff.Easy),
			new BattlePassTask(28, "Купить любой фейерверк", 1, 30, "Деньги на ветер", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(29, "Купить пиво в 24/7", 1, 30, "Светлое нефильтрованное будущее...", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(30, "Использовать парную анимацию", 1, 30, "Взаимодействие - наше всё.", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(32, "Пожать руку 3 людям", 3, 30, "Будем знакомы", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(33, "Провести тест-драйв любого транспорта", 1, 30, "Оценим от 1 до 10", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(34, "Купить любую маску в Mask Shop", 1, 30, "Масочник", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(35, "Поучаствовать в уличной гонке", 1, 30, "Давно тебя не было в уличных гонках", "Сложное задание", 350, BattlePassRewardDiff.Hard),
			new BattlePassTask(38, "Посетить охотничий магазин", 1, 30, "На отшибе", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(39, "Воспользоваться любым банкоматом", 1, 30, "Введите пароль", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(40, "Заправить автомобиль на заправке", 1, 30, "Полный бак!", "Лёгкое задание", 350, BattlePassRewardDiff.Easy),
			new BattlePassTask(42, "Заправить транспорт из канистры", 1, 30, "Залей бензинчика", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(43, "Купить информацию о доме в риэлторском агентстве", 1, 30, "Ловец со стажем", "Сложное задание", 2228, BattlePassRewardDiff.Hard),
			new BattlePassTask(44, "Купить что-нибудь в LS Customs", 1, 30, "Тачку на прокачку", "Сложное задание", 350, BattlePassRewardDiff.Hard),
			new BattlePassTask(45, "Купить связку ключей в 24/7", 1, 30, "Ключник", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(47, "Арендовать палатку на рынке", 1, 30, "Продаван", "Сложное задание", 350, BattlePassRewardDiff.Hard),
			new BattlePassTask(48, "Купить что-нибудь на рынке", 1, 30, "Покупан", "Сложное задание", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(49, "Продлить аренду палатки на рынке", 1, 30, "Настоящий торгаш!", "Сложное задание", 333, BattlePassRewardDiff.Hard),
			new BattlePassTask(50, "Открыть любой кейс", 1, 30, "Испытай удачу", "Сложное задание", 250, BattlePassRewardDiff.Hard),
			new BattlePassTask(51, "Вызвать гос.сотрудника с помощью NPC", 1, 30, "Мне нужна помощь!", "Сложное задание", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(53, "Сделать покупку в Barber Shop", 1, 30, "Привет, подстрижися", "Необычное задание", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(55, "Сыграть в казино", 1, 30, "Еб***** рот этого казино!", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(56, "Повторить чью-нибудь анимацию через G-меню", 1, 30, "Повторюшка", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(57, "Купить что-либо в охотничьем магазине", 1, 30, "Отдалённый магазинчик...", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(58, "Отремонтировать 3 автомобиля, работая механиком", 3, 30, "Старший механик", "Сложное задание", 777, BattlePassRewardDiff.Hard),
			new BattlePassTask(59, "Проехать 15 миль с пассажирами, работая таксистом", 15, 90, "Старший бомбила", "Сложное задание", 777, BattlePassRewardDiff.Hard),
			new BattlePassTask(60, "Получить PayDay", 1, 30, "ЗПха-то капает!", "Лёгкое задание", 420, BattlePassRewardDiff.Easy),
			new BattlePassTask(61, "Покушать чипсов", 1, 30, "Ням-ням чипсеки..", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(62, "Вызвать такси 2 раза", 2, 30, "ТАКСИИИИИИИ!", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(63, "Прокатиться на автобусе и заплатить за проезд", 1, 30, "Передаем за проезд", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(64, "Проехать 100 меток на работе водителя автобуса", 100, 90, "Поворот не туда", "Сложное задание", 666, BattlePassRewardDiff.Hard),
			new BattlePassTask(65, "Вызвать механика", 1, 30, "Чини!", "Лёгкое задание", 777, BattlePassRewardDiff.Easy),
			new BattlePassTask(66, "Выпить пивка", 1, 30, "Не 'Пиво' а 'Пыво'", "Лёгкое задание", 500, BattlePassRewardDiff.Easy),
			new BattlePassTask(67, "Покурить кальян 3 раза", 3, 30, "Дудка дьявола", "Сложное задание", 666, BattlePassRewardDiff.Hard),
			new BattlePassTask(68, "Сделать 5 затяжек вейпа", 5, 30, "Вейп не курят, а парят", "Необычное задание", 500, BattlePassRewardDiff.Medium),
			new BattlePassTask(69, "Покурить бонг", 1, 30, "На часах 4:20...", "Необычное задание", 420, BattlePassRewardDiff.Medium),
			new BattlePassTask(70, "Использовать любую анимацию 3 раза", 3, 30, "Шоу танцы", "Лёгкое задание", 500, BattlePassRewardDiff.Easy),
			new BattlePassTask(71, "Разочек курнуть вейпа", 1, 30, "Миссис Пафф..", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(72, "Совершить трейд с другим игроком", 1, 30, "Функциональный обмен", "Необычное задание", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(74, "Использовать голосовую рацию", 1, 30, "Пшшш... Как слышно?", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(76, "Записать номер телефона в контакты", 1, 30, "ВКонтакте", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(77, "Написать 3 SMS кому-либо, кто находится 'в сети'", 3, 30, "Общение - ключ к успеху", "Сложное задание", 333, BattlePassRewardDiff.Hard),
			new BattlePassTask(78, "Отредактировать имеющийся контакт в телефоне", 1, 30, "Алло, вы шо?", "Сложное задание", 777, BattlePassRewardDiff.Hard),
			new BattlePassTask(84, "Поговорить с NPC в полицейском участке", 1, 30, "This is the police", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(85, "Поговорить с NPC в больнице", 1, 30, "Медицинские рекомендации", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(86, "Пристегнуть ремень безопасности", 1, 30, "Ай болит", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(87, "Открыть капот транспортного средства", 1, 30, "Автомеханик", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(88, "Залезть в багажник автомобиля", 1, 30, "В лес", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(89, "Указать пальцем куда-нибудь 3 раза", 3, 30, "Где?", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(90, "Положить предмет в багажник", 1, 30, "Клад на колёсах", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(91, "Отремонтировать автомобиль, работая механиком", 1, 30, "Механик", "Сложное задание", 444, BattlePassRewardDiff.Hard),
			new BattlePassTask(92, "Доставить 10 сумок с деньгами, работая инкассатором", 10, 90, "Везу деньги бумажные", "Сложное задание", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(93, "Написать рекламу на асфальте (/action)", 1, 30, "Рекламщик 228", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(94, "Вылечить себя с помощью аптечки", 1, 30, "Лови аптечку", "Необычное задание", 500, BattlePassRewardDiff.Medium),
			new BattlePassTask(95, "Накатать 10 миль, будучи пассажиром такси", 10, 30, "Яндекс.Такси", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(97, "Поговорить с любым квестовым персонажем", 1, 30, "Болтун", "Сложное задание", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(98, "Начать лечение в больнице на метке", 1, 30, "Лечи меня полностью!", "Сложное задание", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(99, "Использовать предмет с помощью быстрого слота", 1, 30, "На диком западе...", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(101, "Показать паспорт кому-нибудь", 1, 30, "Papers, Please", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(102, "Кинуть кости в казино (/dice)", 1, 30, "Игроман", "Сложное задание", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(112, "Купить вейп в 24/7", 1, 30, "Vape Nation", "Лёгкое задание", 777, BattlePassRewardDiff.Easy),
			new BattlePassTask(126, "Передать метку водителю, будучи пассажиром", 1, 30, "Вези меня туда!", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(129, "Посети и изучи любой GunShop", 1, 30, "Местная википедия", "Лёгкое задание", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(130, "Купить любое оружие в GunShop", 1, 30, "На забив", "Необычное задание", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(131, "Сыграть в Tank Royale", 1, 30, "Танкисты не спят", "Сложное задание", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(132, "Сыграть в Tank Royale!", 1, 30, "Танкистам ку!", "Сложное задание", 550, BattlePassRewardDiff.Hard),
			new BattlePassTask(134, "Скушать пиццу", 1, 30, "Ммм гавайская...", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(135, "Скушать сендвич", 1, 30, "Сабвей отдыхает!", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(136, "Выпить Sprunk", 1, 30, "Освежает...", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(137, "Скушать хот-дог", 1, 30, "Булочка с сосиской", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(138, "Выпить e-Cola", 1, 30, "Кока", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(139, "Курнуть косячок (использовать наркотики)", 1, 30, "4:20", "Необычное задание", 420, BattlePassRewardDiff.Medium),
			new BattlePassTask(140, "Скушать бургер", 1, 30, "Еду в магазин Гуччи в Санкт-Петербурге", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(147, "Изучить риэлторское агентство", 1, 30, "Ищу хату на НГ", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(148, "Изучить церковь и поговорить со священником", 1, 30, "Ох эта свадьба...", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(149, "Изучить автошколу", 1, 30, "Купи права!", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(150, "Изучить продавца фейерверков", 1, 30, "Зажжём!", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(151, "Изучить склад с личными вещами", 1, 30, "Почта России", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(152, "Изучить продавца питомцев", 1, 30, "Завести друга", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(153, "Изучить Caleb Baker на черном рынке", 1, 30, "Черный-черный рынок", "Лёгкое задание", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(154, "Отвезти 20 посылок, работая почтальоном", 20, 90, "Вам почта! 2.0", "Сложное задание", 333, BattlePassRewardDiff.Hard),
			new BattlePassTask(155, "Проехать 100 меток, работая газонокосильщиком", 100, 90, "Гонщик нелегальный 2.0", "Сложное задание", 333, BattlePassRewardDiff.Hard),
			new BattlePassTask(156, "Починить 80 электроблоков, работая электриком", 80, 90, "Фиксик 2.0", "Сложное задание", 333, BattlePassRewardDiff.Hard),
			new BattlePassTask(157, "Доставить 15 сумок с деньгами, работая инкассатором", 15, 90, "Везу деньги бумажные 2.0", "Сложное задание", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(158, "Получить PayDay 2 раза", 2, 90, "ЗПха-то капает! 2.0", "Необчное задание", 420, BattlePassRewardDiff.Medium),
			new BattlePassTask(159, "Проехать 20 миль с пассажирами, работая таксистом", 20, 90, "Старший бомбила 2.0", "Сложное задание", 777, BattlePassRewardDiff.Hard),
			new BattlePassTask(160, "Проехать 140 меток на работе водителя автобуса", 140, 90, "Поворот не туда 2.0", "Сложное задание", 666, BattlePassRewardDiff.Hard),
        };

		public static List<BattlePassReward> BattlePassAwards = new List<BattlePassReward>
		{
			new BattlePassReward(0, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(1, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(2, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 3),
			new BattlePassReward(3, type: BattlePassRewardType.Money, count: 1000),
			new BattlePassReward(4, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(5, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(5, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(6, type: BattlePassRewardType.Item, itemId: (int)ItemId.Rose, count: 1),
			new BattlePassReward(7, type: BattlePassRewardType.Money, count: 777),
			new BattlePassReward(8, type: BattlePassRewardType.Donate, count: 100),
			new BattlePassReward(9, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(10, type: BattlePassRewardType.Item, itemId: (int)ItemId.Pistol, count: 1),
			new BattlePassReward(11, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(12, type: BattlePassRewardType.Money, count: 777),
			new BattlePassReward(13, type: BattlePassRewardType.Item, itemId: (int)ItemId.Umbrella, count: 1),
			new BattlePassReward(14, type: BattlePassRewardType.Item, itemId: (int)ItemId.AssaultRifleMk2, count: 1),
			new BattlePassReward(15, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(15, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(16, type: BattlePassRewardType.Donate, count: 100),
			new BattlePassReward(17, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(18, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 5),
			new BattlePassReward(19, type: BattlePassRewardType.Vip, itemId: 4, count: 2),
			new BattlePassReward(20, type: BattlePassRewardType.Item, itemId: (int)ItemId.Vape, count: 1, data:"100"),
			new BattlePassReward(21, type: BattlePassRewardType.Donate, count: 100),
			new BattlePassReward(22, type: BattlePassRewardType.Money, count: 777),
			new BattlePassReward(23, type: BattlePassRewardType.Item, itemId: (int)ItemId.Revolver, count: 1),
			new BattlePassReward(24, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(25, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework3, count: 3),
			new BattlePassReward(26, type: BattlePassRewardType.Money, count: 666),
			new BattlePassReward(27, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(27, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(28, type: BattlePassRewardType.Donate, count: 100),
			new BattlePassReward(29, type: BattlePassRewardType.Money, count: 888),
			new BattlePassReward(30, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(31, type: BattlePassRewardType.Item, itemId: (int)ItemId.Gusenberg, count: 1),
			new BattlePassReward(32, type: BattlePassRewardType.Money, count: 1000),
			new BattlePassReward(33, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(34, type: BattlePassRewardType.Donate, count: 100),
			new BattlePassReward(35, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework1, count: 3),
			new BattlePassReward(36, type: BattlePassRewardType.Item, itemId: (int)ItemId.Pickaxe1, count: 1, data:"300"),
			new BattlePassReward(37, type: BattlePassRewardType.Item, itemId: (int)ItemId.LoveNote, count: 1),
			new BattlePassReward(38, type: BattlePassRewardType.Money, count: 1000),
			new BattlePassReward(39, type: BattlePassRewardType.Donate, count: 111),
			new BattlePassReward(40, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(41, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(42, type: BattlePassRewardType.Item, itemId: (int)ItemId.Microphone, count: 1),
			new BattlePassReward(43, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(44, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(44, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(45, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework3, count: 3),
			new BattlePassReward(46, type: BattlePassRewardType.Donate, count: 100),
			new BattlePassReward(47, type: BattlePassRewardType.Money, count: 777),
			new BattlePassReward(48, type: BattlePassRewardType.Item, itemId: (int)ItemId.SMG, count: 1),
			new BattlePassReward(49, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(50, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 5),
			new BattlePassReward(51, type: BattlePassRewardType.Item, itemId: (int)ItemId.Revolver, count: 1),
			new BattlePassReward(52, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 3),
			new BattlePassReward(53, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(53, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(54, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(55, type: BattlePassRewardType.Item, itemId: (int)ItemId.Rose, count: 1),
			new BattlePassReward(56, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(57, type: BattlePassRewardType.Item, itemId: (int)ItemId.Musket, count: 1),
			new BattlePassReward(58, type: BattlePassRewardType.Donate, count: 111),
			new BattlePassReward(59, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(60, type: BattlePassRewardType.Item, itemId: (int)ItemId.Pistol, count: 1),
			new BattlePassReward(61, type: BattlePassRewardType.Item, itemId: (int)ItemId.WorkAxe, count: 1, data:"1250"),
			new BattlePassReward(62, type: BattlePassRewardType.Money, count: 777),
			new BattlePassReward(63, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(63, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(64, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework3, count: 3),
			new BattlePassReward(65, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(66, type: BattlePassRewardType.Donate, count: 111),
			new BattlePassReward(67, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(68, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(69, type: BattlePassRewardType.Item, itemId: (int)ItemId.AssaultShotgun, count: 1),
			new BattlePassReward(70, type: BattlePassRewardType.Item, itemId: (int)ItemId.Guitar, count: 1),
			new BattlePassReward(71, type: BattlePassRewardType.Money, count: 777),
			new BattlePassReward(72, type: BattlePassRewardType.Donate, count: 100),
			new BattlePassReward(73, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(73, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(74, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(75, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(76, type: BattlePassRewardType.Money, count: 1111),
			new BattlePassReward(77, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework4, count: 3),
			new BattlePassReward(78, type: BattlePassRewardType.Donate, count: 120),
			new BattlePassReward(79, type: BattlePassRewardType.Money, count: 1111),
			new BattlePassReward(80, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(81, type: BattlePassRewardType.Money, count: 1111),
			new BattlePassReward(82, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 5),
			new BattlePassReward(83, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(84, type: BattlePassRewardType.Donate, count: 120),
			new BattlePassReward(85, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework2, count: 3),
			new BattlePassReward(86, type: BattlePassRewardType.Item, itemId: (int)ItemId.Pickaxe2, count: 1, data:"1248"),
			new BattlePassReward(87, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(88, type: BattlePassRewardType.Money, count: 1111),
			new BattlePassReward(89, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(90, type: BattlePassRewardType.Donate, count: 120),
			new BattlePassReward(91, type: BattlePassRewardType.Item, itemId: (int)ItemId.SMGMk2, count: 1),
			new BattlePassReward(92, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(93, type: BattlePassRewardType.Money, count: 1228),
			new BattlePassReward(94, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(94, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(95, type: BattlePassRewardType.Donate, count: 120),
			new BattlePassReward(96, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(97, type: BattlePassRewardType.Money, count: 1228),
			new BattlePassReward(98, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework4, count: 3),
			new BattlePassReward(99, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(100, type: BattlePassRewardType.Item, itemId: (int)ItemId.SNSPistol, count: 1),
			new BattlePassReward(101, type: BattlePassRewardType.Donate, count: 120),
			new BattlePassReward(102, type: BattlePassRewardType.Money, count: 1337),
			new BattlePassReward(103, type: BattlePassRewardType.Item, itemId: (int)ItemId.VintagePistol, count: 1),
			new BattlePassReward(104, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(105, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(106, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(106, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(107, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework4, count: 3),
			new BattlePassReward(108, type: BattlePassRewardType.Donate, count: 120),
			new BattlePassReward(109, type: BattlePassRewardType.Money, count: 1337),
			new BattlePassReward(110, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 5),
			new BattlePassReward(111, type: BattlePassRewardType.Item, itemId: (int)ItemId.Camera, count: 1),
			new BattlePassReward(112, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(113, type: BattlePassRewardType.Item, itemId: (int)ItemId.Bong, count: 1, data:"420"),
			new BattlePassReward(114, type: BattlePassRewardType.Donate, count: 120),
			new BattlePassReward(115, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework4, count: 3),
			new BattlePassReward(116, type: BattlePassRewardType.Item, itemId: (int)ItemId.Pickaxe3, count: 1, data: "2250"),
			new BattlePassReward(117, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(118, type: BattlePassRewardType.Money, count: 1337),
			new BattlePassReward(119, type: BattlePassRewardType.Item, itemId: (int)ItemId.Hookah, count: 1, data:"1000"),
			new BattlePassReward(120, type: BattlePassRewardType.Donate, count: 200),
			new BattlePassReward(121, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(121, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(122, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(123, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(124, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
			new BattlePassReward(125, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
			new BattlePassReward(126, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case7, count: 1),
			new BattlePassReward(127, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(127, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(128, type: BattlePassRewardType.Donate, count: 420),
			new BattlePassReward(129, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
			new BattlePassReward(130, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
			new BattlePassReward(131, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"apriora", name:"Приора", count: 1),
		};

		public static List<BattlePassReward> BattlePassAwardsPremium = new List<BattlePassReward>
		{
			new BattlePassReward(0, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(1, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "165_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(1, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "174_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(2, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(3, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "468_0_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(3, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "483_0_False", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(4, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "166_0_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(4, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "175_0_False", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(5, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "210_0_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(5, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "210_0_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(6, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(6, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(7, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "467_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(7, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "482_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(8, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
            new BattlePassReward(9, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "469_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(9, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "484_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(10, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "164_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(10, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "176_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(11, type: BattlePassRewardType.Item, itemId: (int)ItemId.CombatMGMk2, count: 1),
            new BattlePassReward(12, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "163_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(12, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "173_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(13, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_0_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(13, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_0_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(14, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(15, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "463_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(15, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "480_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(16, type: BattlePassRewardType.Vip, itemId: 4, count: 7),
            new BattlePassReward(17, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "165_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(17, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "174_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(18, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
            new BattlePassReward(19, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "462_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(19, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "485_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(20, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(21, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_1_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(21, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_1_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(22, type: BattlePassRewardType.Item, itemId: (int)ItemId.FlareGun, count: 1),
            new BattlePassReward(23, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "464_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(23, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "481_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(24, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(24, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(25, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "163_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(25, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "173_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(26, type: BattlePassRewardType.Donate, count: 228),
            new BattlePassReward(27, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "468_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(27, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "483_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(28, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "166_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(28, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "175_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(29, type: BattlePassRewardType.Vip, itemId: 4, count: 7),
            new BattlePassReward(30, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_2_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(30, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_2_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(31, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(31, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(32, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "467_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(32, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "482_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(33, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_2_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(33, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_2_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(34, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(35, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "462_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(35, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "485_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(36, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(37, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_1_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(37, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_1_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(38, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(38, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(39, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "465_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(39, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "479_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(40, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(41, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_0_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(41, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_0_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(42, type: BattlePassRewardType.Vip, itemId: 4, count: 7),
            new BattlePassReward(43, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "469_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(43, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "484_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(44, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "164_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(44, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "176_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(45, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
            new BattlePassReward(46, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_3_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(46, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_3_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(47, type: BattlePassRewardType.Item, itemId: (int)ItemId.HeavySniperMk2, count: 1),
            new BattlePassReward(48, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "464_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(48, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "481_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(49, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_3_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(49, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_3_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(50, type: BattlePassRewardType.Donate, count: 228),
            new BattlePassReward(51, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "465_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(51, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "479_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(52, type: BattlePassRewardType.Money, count: 5000),
            new BattlePassReward(53, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "210_1_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(53, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "210_1_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(54, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "165_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(54, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "174_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(55, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
            new BattlePassReward(56, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "467_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(56, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "482_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(57, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(58, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_4_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(58, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_4_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(59, type: BattlePassRewardType.Vip, itemId: 4, count: 7),
            new BattlePassReward(60, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "468_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(60, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "483_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(61, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "166_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(61, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "175_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(62, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_5_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(62, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_5_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(63, type: BattlePassRewardType.Item, itemId: (int)ItemId.HeavyShotgun, count: 1),
            new BattlePassReward(64, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "466_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(64, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "486_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(65, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(66, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_4_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(66, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_4_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(67, type: BattlePassRewardType.Donate, count: 228),
            new BattlePassReward(68, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "463_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(68, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "480_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(69, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(70, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_6_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(70, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_6_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(71, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(71, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(72, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "463_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(72, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "480_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(73, type: BattlePassRewardType.Vip, itemId: 4, count: 7),
            new BattlePassReward(74, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "165_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(74, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "174_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(75, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(76, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "469_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(76, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "484_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(77, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "164_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(77, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "176_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(78, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
            new BattlePassReward(79, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "464_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(79, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "481_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(80, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_7_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(80, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_7_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(81, type: BattlePassRewardType.Vip, itemId: 4, count: 7),
            new BattlePassReward(82, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "465_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(82, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "479_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(83, type: BattlePassRewardType.Donate, count: 228),
            new BattlePassReward(84, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(85, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "466_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(85, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "486_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(86, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_5_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(86, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_5_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(87, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(87, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(88, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "462_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(88, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "485_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(89, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(90, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_8_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(90, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_8_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(91, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "467_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(91, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "482_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(92, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
            new BattlePassReward(93, type: BattlePassRewardType.Donate, count: 228),
            new BattlePassReward(94, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "468_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(94, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "483_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(95, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "166_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(95, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "175_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(96, type: BattlePassRewardType.Vip, itemId: 4, count: 10),
            new BattlePassReward(97, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(97, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(98, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "466_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(98, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "486_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(99, type: BattlePassRewardType.Item, itemId: (int)ItemId.RevolverMk2, count: 1),
            new BattlePassReward(100, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_9_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(100, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_9_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(101, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
            new BattlePassReward(102, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "465_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(102, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "479_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(103, type: BattlePassRewardType.Item, itemId: (int)ItemId.MarksmanRifle, count: 1),
            new BattlePassReward(104, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "163_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(104, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "173_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(105, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(105, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(106, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "464_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(106, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "481_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(107, type: BattlePassRewardType.Donate, count: 250),
            new BattlePassReward(108, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(109, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "469_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(109, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "484_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(110, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "164_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(110, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "176_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(111, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(111, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(112, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "165_4_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(112, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "174_4_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(113, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
            new BattlePassReward(114, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "467_4_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(114, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "482_4_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(115, type: BattlePassRewardType.Vip, itemId: 4, count: 7),
            new BattlePassReward(116, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case7, count: 1),
            new BattlePassReward(117, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "463_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(117, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "480_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(118, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(118, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(119, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "165_5_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(119, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "174_5_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(120, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(120, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(121, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "467_5_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(121, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "482_5_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(122, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_6_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(122, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_6_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(123, type: BattlePassRewardType.Donate, count: 333),
            new BattlePassReward(124, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case7, count: 1),
            new BattlePassReward(125, type: BattlePassRewardType.Vip, itemId: 4, count: 10),
            new BattlePassReward(126, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "210_2_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(126, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "210_2_True", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(127, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "466_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(127, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "486_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(128, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(128, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(129, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
            new BattlePassReward(130, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_7_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(130, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_7_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(131, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, count: 1, data: "ecto1", name:"Эктомобиль"),
		};

    }
}