//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace Database
{
	/// <summary>
	/// Database       : ra3_mainconfig
	/// Data Source    : 127.0.0.1
	/// Server Version : 5.5.5-10.4.32-MariaDB
	/// </summary>
	public partial class ConfigBD : LinqToDB.Data.DataConnection
	{
		public ITable<BarberFemaleBeards>       BarberFemaleBeard        { get { return this.GetTable<BarberFemaleBeards>(); } }
		public ITable<BarberFemaleBodies>       BarberFemaleBody         { get { return this.GetTable<BarberFemaleBodies>(); } }
		public ITable<BarberFemaleEyebrows>     BarberFemaleEyebrows     { get { return this.GetTable<BarberFemaleEyebrows>(); } }
		public ITable<BarberFemaleEyes>         BarberFemaleEyes         { get { return this.GetTable<BarberFemaleEyes>(); } }
		public ITable<BarberFemaleHair>         BarberFemaleHair         { get { return this.GetTable<BarberFemaleHair>(); } }
		public ITable<BarberFemaleLips>         BarberFemaleLips         { get { return this.GetTable<BarberFemaleLips>(); } }
		public ITable<BarberFemaleMakeups>      BarberFemaleMakeup       { get { return this.GetTable<BarberFemaleMakeups>(); } }
		public ITable<BarberFemalePalettes>     BarberFemalePalette      { get { return this.GetTable<BarberFemalePalettes>(); } }
		public ITable<BarberMaleBeards>         BarberMaleBeard          { get { return this.GetTable<BarberMaleBeards>(); } }
		public ITable<BarberMaleBodies>         BarberMaleBody           { get { return this.GetTable<BarberMaleBodies>(); } }
		public ITable<BarberMaleEyebrows>       BarberMaleEyebrows       { get { return this.GetTable<BarberMaleEyebrows>(); } }
		public ITable<BarberMaleEyes>           BarberMaleEyes           { get { return this.GetTable<BarberMaleEyes>(); } }
		public ITable<BarberMaleHair>           BarberMaleHair           { get { return this.GetTable<BarberMaleHair>(); } }
		public ITable<BarberMaleLips>           BarberMaleLips           { get { return this.GetTable<BarberMaleLips>(); } }
		public ITable<BarberMaleMakeups>        BarberMaleMakeup         { get { return this.GetTable<BarberMaleMakeups>(); } }
		public ITable<BarberMalePalettes>       BarberMalePalette        { get { return this.GetTable<BarberMalePalettes>(); } }
		public ITable<Bpawards>                 Bpawards                 { get { return this.GetTable<Bpawards>(); } }
		public ITable<Bpawardsolds>             Bpawardsold              { get { return this.GetTable<Bpawardsolds>(); } }
		public ITable<Bpawardspremiumolds>      Bpawardspremiumold       { get { return this.GetTable<Bpawardspremiumolds>(); } }
		public ITable<Bpawardspremiums>         Bpawardspremium          { get { return this.GetTable<Bpawardspremiums>(); } }
		public ITable<Bptasks>                  Bptask                   { get { return this.GetTable<Bptasks>(); } }
		public ITable<BusProducts>              BusProducts              { get { return this.GetTable<BusProducts>(); } }
		public ITable<ClothesBugs>              ClothesBugs              { get { return this.GetTable<ClothesBugs>(); } }
		public ITable<ClothesFemaleAccessories> ClothesFemaleAccessories { get { return this.GetTable<ClothesFemaleAccessories>(); } }
		public ITable<ClothesFemaleBodyarmors>  ClothesFemaleBodyarmors  { get { return this.GetTable<ClothesFemaleBodyarmors>(); } }
		public ITable<ClothesFemaleBracelets>   ClothesFemaleBracelets   { get { return this.GetTable<ClothesFemaleBracelets>(); } }
		public ITable<ClothesFemaleDecals>      ClothesFemaleDecals      { get { return this.GetTable<ClothesFemaleDecals>(); } }
		public ITable<ClothesFemaleEars>        ClothesFemaleEars        { get { return this.GetTable<ClothesFemaleEars>(); } }
		public ITable<ClothesFemaleGlasses>     ClothesFemaleGlasses     { get { return this.GetTable<ClothesFemaleGlasses>(); } }
		public ITable<ClothesFemaleHats>        ClothesFemaleHats        { get { return this.GetTable<ClothesFemaleHats>(); } }
		public ITable<ClothesFemaleLegs>        ClothesFemaleLegs        { get { return this.GetTable<ClothesFemaleLegs>(); } }
		public ITable<ClothesFemaleMasks>       ClothesFemaleMasks       { get { return this.GetTable<ClothesFemaleMasks>(); } }
		public ITable<ClothesFemaleShoes>       ClothesFemaleShoes       { get { return this.GetTable<ClothesFemaleShoes>(); } }
		public ITable<ClothesFemaleTops>        ClothesFemaleTops        { get { return this.GetTable<ClothesFemaleTops>(); } }
		public ITable<ClothesFemaleTorsos>      ClothesFemaleTorsos      { get { return this.GetTable<ClothesFemaleTorsos>(); } }
		public ITable<ClothesFemaleWatches>     ClothesFemaleWatches     { get { return this.GetTable<ClothesFemaleWatches>(); } }
		public ITable<ClothesMaleAccessories>   ClothesMaleAccessories   { get { return this.GetTable<ClothesMaleAccessories>(); } }
		public ITable<ClothesMaleBodyarmors>    ClothesMaleBodyarmors    { get { return this.GetTable<ClothesMaleBodyarmors>(); } }
		public ITable<ClothesMaleBracelets>     ClothesMaleBracelets     { get { return this.GetTable<ClothesMaleBracelets>(); } }
		public ITable<ClothesMaleDecals>        ClothesMaleDecals        { get { return this.GetTable<ClothesMaleDecals>(); } }
		public ITable<ClothesMaleEars>          ClothesMaleEars          { get { return this.GetTable<ClothesMaleEars>(); } }
		public ITable<ClothesMaleGlasses>       ClothesMaleGlasses       { get { return this.GetTable<ClothesMaleGlasses>(); } }
		public ITable<ClothesMaleHats>          ClothesMaleHats          { get { return this.GetTable<ClothesMaleHats>(); } }
		public ITable<ClothesMaleLegs>          ClothesMaleLegs          { get { return this.GetTable<ClothesMaleLegs>(); } }
		public ITable<ClothesMaleMasks>         ClothesMaleMasks         { get { return this.GetTable<ClothesMaleMasks>(); } }
		public ITable<ClothesMaleShoes>         ClothesMaleShoes         { get { return this.GetTable<ClothesMaleShoes>(); } }
		public ITable<ClothesMaleTops>          ClothesMaleTops          { get { return this.GetTable<ClothesMaleTops>(); } }
		public ITable<ClothesMaleTorsos>        ClothesMaleTorsos        { get { return this.GetTable<ClothesMaleTorsos>(); } }
		public ITable<ClothesMaleWatches>       ClothesMaleWatches       { get { return this.GetTable<ClothesMaleWatches>(); } }
		public ITable<ClothesMasks>             ClothesMasks             { get { return this.GetTable<ClothesMasks>(); } }
		public ITable<Everydayawards>           Everydayaward            { get { return this.GetTable<Everydayawards>(); } }
		public ITable<Ores>                     Ores                     { get { return this.GetTable<Ores>(); } }
		public ITable<Roulettes>                Roulette                 { get { return this.GetTable<Roulettes>(); } }
		public ITable<Systemstates>             Systemstate              { get { return this.GetTable<Systemstates>(); } }
		public ITable<TattooHeads>              TattooHead               { get { return this.GetTable<TattooHeads>(); } }
		public ITable<TattooLeftarms>           TattooLeftarm            { get { return this.GetTable<TattooLeftarms>(); } }
		public ITable<TattooLeftlegs>           TattooLeftleg            { get { return this.GetTable<TattooLeftlegs>(); } }
		public ITable<TattooRightarms>          TattooRightarm           { get { return this.GetTable<TattooRightarms>(); } }
		public ITable<TattooRightlegs>          TattooRightleg           { get { return this.GetTable<TattooRightlegs>(); } }
		public ITable<TattooTorsoes>            TattooTorso              { get { return this.GetTable<TattooTorsoes>(); } }

		public ConfigBD()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public ConfigBD(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public ConfigBD(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("barber_female_beard")]
	public partial class BarberFemaleBeards
	{
		[Column("id"),         PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull             ] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull             ] public int    Cvariation { get; set; } // int(11)
		[Column("tname"),      NotNull             ] public string Tname      { get; set; } // varchar(50)
		[Column("name"),       NotNull             ] public string Name       { get; set; } // varchar(50)
		[Column("price"),      NotNull             ] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull             ] public int    Donate     { get; set; } // int(11)
	}

	[Table("barber_female_body")]
	public partial class BarberFemaleBodies
	{
		[Column("id"),         PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull             ] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull             ] public int    Cvariation { get; set; } // int(11)
		[Column("tname"),      NotNull             ] public string Tname      { get; set; } // varchar(50)
		[Column("name"),       NotNull             ] public string Name       { get; set; } // varchar(50)
		[Column("price"),      NotNull             ] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull             ] public int    Donate     { get; set; } // int(11)
	}

	[Table("barber_female_eyebrows")]
	public partial class BarberFemaleEyebrows
	{
		[Column("id"),         PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull             ] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull             ] public int    Cvariation { get; set; } // int(11)
		[Column("tname"),      NotNull             ] public string Tname      { get; set; } // varchar(50)
		[Column("name"),       NotNull             ] public string Name       { get; set; } // varchar(50)
		[Column("price"),      NotNull             ] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull             ] public int    Donate     { get; set; } // int(11)
	}

	[Table("barber_female_eyes")]
	public partial class BarberFemaleEyes
	{
		[Column("id"),         PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull             ] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull             ] public int    Cvariation { get; set; } // int(11)
		[Column("tname"),      NotNull             ] public string Tname      { get; set; } // varchar(50)
		[Column("name"),       NotNull             ] public string Name       { get; set; } // varchar(50)
		[Column("price"),      NotNull             ] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull             ] public int    Donate     { get; set; } // int(11)
	}

	[Table("barber_female_hair")]
	public partial class BarberFemaleHair
	{
		[Column("id"),         PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull             ] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull             ] public int    Cvariation { get; set; } // int(11)
		[Column("tname"),      NotNull             ] public string Tname      { get; set; } // varchar(50)
		[Column("name"),       NotNull             ] public string Name       { get; set; } // varchar(50)
		[Column("price"),      NotNull             ] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull             ] public int    Donate     { get; set; } // int(11)
	}

	[Table("barber_female_lips")]
	public partial class BarberFemaleLips
	{
		[Column("id"),         PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull             ] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull             ] public int    Cvariation { get; set; } // int(11)
		[Column("tname"),      NotNull             ] public string Tname      { get; set; } // varchar(50)
		[Column("name"),       NotNull             ] public string Name       { get; set; } // varchar(50)
		[Column("price"),      NotNull             ] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull             ] public int    Donate     { get; set; } // int(11)
	}

	[Table("barber_female_makeup")]
	public partial class BarberFemaleMakeups
	{
		[Column("id"),         PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull             ] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull             ] public int    Cvariation { get; set; } // int(11)
		[Column("tname"),      NotNull             ] public string Tname      { get; set; } // varchar(50)
		[Column("name"),       NotNull             ] public string Name       { get; set; } // varchar(50)
		[Column("price"),      NotNull             ] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull             ] public int    Donate     { get; set; } // int(11)
	}

	[Table("barber_female_palette")]
	public partial class BarberFemalePalettes
	{
		[Column("id"),         PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull             ] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull             ] public int    Cvariation { get; set; } // int(11)
		[Column("tname"),      NotNull             ] public string Tname      { get; set; } // varchar(50)
		[Column("name"),       NotNull             ] public string Name       { get; set; } // varchar(50)
		[Column("price"),      NotNull             ] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull             ] public int    Donate     { get; set; } // int(11)
	}

	[Table("barber_male_beard")]
	public partial class BarberMaleBeards
	{
		[Column("id"),         PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull             ] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull             ] public int    Cvariation { get; set; } // int(11)
		[Column("tname"),      NotNull             ] public string Tname      { get; set; } // varchar(50)
		[Column("name"),       NotNull             ] public string Name       { get; set; } // varchar(50)
		[Column("price"),      NotNull             ] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull             ] public int    Donate     { get; set; } // int(11)
	}

	[Table("barber_male_body")]
	public partial class BarberMaleBodies
	{
		[Column("id"),         PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull             ] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull             ] public int    Cvariation { get; set; } // int(11)
		[Column("tname"),      NotNull             ] public string Tname      { get; set; } // varchar(50)
		[Column("name"),       NotNull             ] public string Name       { get; set; } // varchar(50)
		[Column("price"),      NotNull             ] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull             ] public int    Donate     { get; set; } // int(11)
	}

	[Table("barber_male_eyebrows")]
	public partial class BarberMaleEyebrows
	{
		[Column("id"),         PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull             ] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull             ] public int    Cvariation { get; set; } // int(11)
		[Column("tname"),      NotNull             ] public string Tname      { get; set; } // varchar(50)
		[Column("name"),       NotNull             ] public string Name       { get; set; } // varchar(50)
		[Column("price"),      NotNull             ] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull             ] public int    Donate     { get; set; } // int(11)
	}

	[Table("barber_male_eyes")]
	public partial class BarberMaleEyes
	{
		[Column("id"),         PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull             ] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull             ] public int    Cvariation { get; set; } // int(11)
		[Column("tname"),      NotNull             ] public string Tname      { get; set; } // varchar(50)
		[Column("name"),       NotNull             ] public string Name       { get; set; } // varchar(50)
		[Column("price"),      NotNull             ] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull             ] public int    Donate     { get; set; } // int(11)
	}

	[Table("barber_male_hair")]
	public partial class BarberMaleHair
	{
		[Column("id"),         PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull             ] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull             ] public int    Cvariation { get; set; } // int(11)
		[Column("tname"),      NotNull             ] public string Tname      { get; set; } // varchar(50)
		[Column("name"),       NotNull             ] public string Name       { get; set; } // varchar(50)
		[Column("price"),      NotNull             ] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull             ] public int    Donate     { get; set; } // int(11)
	}

	[Table("barber_male_lips")]
	public partial class BarberMaleLips
	{
		[Column("id"),         PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull             ] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull             ] public int    Cvariation { get; set; } // int(11)
		[Column("tname"),      NotNull             ] public string Tname      { get; set; } // varchar(50)
		[Column("name"),       NotNull             ] public string Name       { get; set; } // varchar(50)
		[Column("price"),      NotNull             ] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull             ] public int    Donate     { get; set; } // int(11)
	}

	[Table("barber_male_makeup")]
	public partial class BarberMaleMakeups
	{
		[Column("id"),         PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull             ] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull             ] public int    Cvariation { get; set; } // int(11)
		[Column("tname"),      NotNull             ] public string Tname      { get; set; } // varchar(50)
		[Column("name"),       NotNull             ] public string Name       { get; set; } // varchar(50)
		[Column("price"),      NotNull             ] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull             ] public int    Donate     { get; set; } // int(11)
	}

	[Table("barber_male_palette")]
	public partial class BarberMalePalettes
	{
		[Column("id"),         PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull             ] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull             ] public int    Cvariation { get; set; } // int(11)
		[Column("tname"),      NotNull             ] public string Tname      { get; set; } // varchar(50)
		[Column("name"),       NotNull             ] public string Name       { get; set; } // varchar(50)
		[Column("price"),      NotNull             ] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull             ] public int    Donate     { get; set; } // int(11)
	}

	[Table("bpawards")]
	public partial class Bpawards
	{
		[Column("id"),     Nullable] public int?   Id     { get; set; } // int(11)
		[Column("type"),   Nullable] public sbyte? Type   { get; set; } // tinyint(2)
		[Column("itemId"), Nullable] public int?   ItemId { get; set; } // int(11)
		[Column("count"),  Nullable] public int?   Count  { get; set; } // int(11)
		[Column("data"),   Nullable] public string Data   { get; set; } // varchar(50)
		[Column("gender"), Nullable] public sbyte? Gender { get; set; } // tinyint(2)
	}

	[Table("bpawardsold")]
	public partial class Bpawardsolds
	{
		[Column("id"),     Nullable] public int?   Id     { get; set; } // int(11)
		[Column("type"),   Nullable] public sbyte? Type   { get; set; } // tinyint(2)
		[Column("itemId"), Nullable] public int?   ItemId { get; set; } // int(11)
		[Column("count"),  Nullable] public int?   Count  { get; set; } // int(11)
		[Column("data"),   Nullable] public string Data   { get; set; } // varchar(50)
		[Column("gender"), Nullable] public sbyte? Gender { get; set; } // tinyint(2)
	}

	[Table("bpawardspremiumold")]
	public partial class Bpawardspremiumolds
	{
		[Column("id"),     Nullable] public int?   Id     { get; set; } // int(11)
		[Column("type"),   Nullable] public sbyte? Type   { get; set; } // tinyint(2)
		[Column("itemId"), Nullable] public int?   ItemId { get; set; } // int(11)
		[Column("count"),  Nullable] public int?   Count  { get; set; } // int(11)
		[Column("data"),   Nullable] public string Data   { get; set; } // varchar(50)
		[Column("gender"), Nullable] public sbyte? Gender { get; set; } // tinyint(2)
	}

	[Table("bpawardspremium")]
	public partial class Bpawardspremiums
	{
		[Column("id"),     Nullable] public int?   Id     { get; set; } // int(11)
		[Column("type"),   Nullable] public sbyte? Type   { get; set; } // tinyint(2)
		[Column("itemId"), Nullable] public int?   ItemId { get; set; } // int(11)
		[Column("count"),  Nullable] public int?   Count  { get; set; } // int(11)
		[Column("data"),   Nullable] public string Data   { get; set; } // varchar(50)
		[Column("gender"), Nullable] public sbyte? Gender { get; set; } // tinyint(2)
	}

	[Table("bptask")]
	public partial class Bptasks
	{
		[Column("id"),    Nullable] public int? Id    { get; set; } // int(11)
		[Column("money"), Nullable] public int? Money { get; set; } // int(11)
	}

	[Table("bus_products")]
	public partial class BusProducts
	{
		[Column("name"),       PrimaryKey, NotNull] public string Name       { get; set; } // varchar(86)
		[Column("price"),                  NotNull] public int    Price      { get; set; } // int(11)
		[Column("otherPrice"),             NotNull] public int    OtherPrice { get; set; } // int(11)
		[Column("percent"),                NotNull] public sbyte  Percent    { get; set; } // tinyint(4)
		[Column("maxCount"),               NotNull] public int    MaxCount   { get; set; } // int(11)
		[Column("type"),                   NotNull] public sbyte  Type       { get; set; } // tinyint(2)
		[Column("itemId"),                 NotNull] public int    ItemId     { get; set; } // int(11)
		[Column("toggled"),                NotNull] public bool   Toggled    { get; set; } // tinyint(1)
	}

	[Table("clothes_bugs")]
	public partial class ClothesBugs
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
		[Column("maxSlots"),   NotNull] public int    MaxSlots   { get; set; } // int(11)
	}

	[Table("clothes_female_accessories")]
	public partial class ClothesFemaleAccessories
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("category"),   NotNull] public string Category   { get; set; } // text
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
	}

	[Table("clothes_female_bodyarmors")]
	public partial class ClothesFemaleBodyarmors
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("category"),   NotNull] public string Category   { get; set; } // text
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
	}

	[Table("clothes_female_bracelets")]
	public partial class ClothesFemaleBracelets
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("category"),   NotNull] public string Category   { get; set; } // text
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
	}

	[Table("clothes_female_decals")]
	public partial class ClothesFemaleDecals
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("category"),   NotNull] public string Category   { get; set; } // text
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
	}

	[Table("clothes_female_ears")]
	public partial class ClothesFemaleEars
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("category"),   NotNull] public string Category   { get; set; } // text
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
	}

	[Table("clothes_female_glasses")]
	public partial class ClothesFemaleGlasses
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("category"),   NotNull] public string Category   { get; set; } // text
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
	}

	[Table("clothes_female_hats")]
	public partial class ClothesFemaleHats
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("clean_hair"), NotNull] public bool   CleanHair  { get; set; } // tinyint(1)
		[Column("similar"),    NotNull] public int    Similar    { get; set; } // int(11)
		[Column("category"),   NotNull] public string Category   { get; set; } // text
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
	}

	[Table("clothes_female_legs")]
	public partial class ClothesFemaleLegs
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("underwear"),  NotNull] public bool   Underwear  { get; set; } // tinyint(1)
		[Column("category"),   NotNull] public string Category   { get; set; } // text
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
	}

	[Table("clothes_female_masks")]
	public partial class ClothesFemaleMasks
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("isHair"),     NotNull] public bool   IsHair     { get; set; } // tinyint(1)
		[Column("isHat"),      NotNull] public bool   IsHat      { get; set; } // tinyint(1)
		[Column("isGlasses"),  NotNull] public bool   IsGlasses  { get; set; } // tinyint(1)
		[Column("category"),   NotNull] public string Category   { get; set; } // mediumtext
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
		[Column("gender"),     NotNull] public sbyte  Gender     { get; set; } // tinyint(2)
	}

	[Table("clothes_female_shoes")]
	public partial class ClothesFemaleShoes
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("category"),   NotNull] public string Category   { get; set; } // text
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
	}

	[Table("clothes_female_tops")]
	public partial class ClothesFemaleTops
	{
		[Column("id"),                        NotNull] public int    Id                      { get; set; } // int(11)
		[Column("variation"),                 NotNull] public int    Variation               { get; set; } // int(11)
		[Column("cvariation"),                NotNull] public int    Cvariation              { get; set; } // int(11)
		[Column("torso"),                     NotNull] public int    Torso                   { get; set; } // int(11)
		[Column("textures"),                  NotNull] public string Textures                { get; set; } // mediumtext
		[Column("similar"),                   NotNull] public int    Similar                 { get; set; } // int(11)
		/// <summary>
		/// -1 - Не может быть вверхом, 0 - полностью закрыта, 1 - Полностью растегнута, 2 - растегнута на половину
		/// </summary>
		[Column("type"),                      NotNull] public short  Type                    { get; set; } // smallint(6)
		[Column("undershirt"),                NotNull] public int    Undershirt              { get; set; } // int(11)
		[Column("undershirt_buttoned"),       NotNull] public int    UndershirtButtoned      { get; set; } // int(11)
		[Column("undershirt_torso"),          NotNull] public int    UndershirtTorso         { get; set; } // int(11)
		[Column("undershirt_buttoned_torso"), NotNull] public int    UndershirtButtonedTorso { get; set; } // int(11)
		[Column("isClearLegs"),               NotNull] public bool   IsClearLegs             { get; set; } // tinyint(1)
		[Column("category"),                  NotNull] public string Category                { get; set; } // mediumtext
		[Column("price"),                     NotNull] public int    Price                   { get; set; } // int(11)
		[Column("donate"),                    NotNull] public int    Donate                  { get; set; } // int(11)
	}

	[Table("clothes_female_torsos")]
	public partial class ClothesFemaleTorsos
	{
		[Column("id"),         PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull             ] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull             ] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull             ] public string Textures   { get; set; } // text
		[Column("price"),      NotNull             ] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull             ] public int    Donate     { get; set; } // int(11)
		[Column("torso"),      NotNull             ] public string Torso      { get; set; } // text
	}

	[Table("clothes_female_watches")]
	public partial class ClothesFemaleWatches
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("category"),   NotNull] public string Category   { get; set; } // text
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
	}

	[Table("clothes_male_accessories")]
	public partial class ClothesMaleAccessories
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("category"),   NotNull] public string Category   { get; set; } // text
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
	}

	[Table("clothes_male_bodyarmors")]
	public partial class ClothesMaleBodyarmors
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("category"),   NotNull] public string Category   { get; set; } // text
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
	}

	[Table("clothes_male_bracelets")]
	public partial class ClothesMaleBracelets
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("category"),   NotNull] public string Category   { get; set; } // text
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
	}

	[Table("clothes_male_decals")]
	public partial class ClothesMaleDecals
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("category"),   NotNull] public string Category   { get; set; } // text
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
	}

	[Table("clothes_male_ears")]
	public partial class ClothesMaleEars
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("category"),   NotNull] public string Category   { get; set; } // text
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
	}

	[Table("clothes_male_glasses")]
	public partial class ClothesMaleGlasses
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("category"),   NotNull] public string Category   { get; set; } // text
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
	}

	[Table("clothes_male_hats")]
	public partial class ClothesMaleHats
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("clean_hair"), NotNull] public bool   CleanHair  { get; set; } // tinyint(1)
		[Column("similar"),    NotNull] public int    Similar    { get; set; } // int(11)
		[Column("category"),   NotNull] public string Category   { get; set; } // text
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
	}

	[Table("clothes_male_legs")]
	public partial class ClothesMaleLegs
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("underwear"),  NotNull] public bool   Underwear  { get; set; } // tinyint(1)
		[Column("category"),   NotNull] public string Category   { get; set; } // text
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
	}

	[Table("clothes_male_masks")]
	public partial class ClothesMaleMasks
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("isHair"),     NotNull] public bool   IsHair     { get; set; } // tinyint(1)
		[Column("isHat"),      NotNull] public bool   IsHat      { get; set; } // tinyint(1)
		[Column("isGlasses"),  NotNull] public bool   IsGlasses  { get; set; } // tinyint(1)
		[Column("category"),   NotNull] public string Category   { get; set; } // mediumtext
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
		[Column("gender"),     NotNull] public sbyte  Gender     { get; set; } // tinyint(2)
	}

	[Table("clothes_male_shoes")]
	public partial class ClothesMaleShoes
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("category"),   NotNull] public string Category   { get; set; } // text
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
	}

	[Table("clothes_male_tops")]
	public partial class ClothesMaleTops
	{
		[Column("id"),                        NotNull] public int    Id                      { get; set; } // int(11)
		[Column("variation"),                 NotNull] public int    Variation               { get; set; } // int(11)
		[Column("cvariation"),                NotNull] public int    Cvariation              { get; set; } // int(11)
		[Column("torso"),                     NotNull] public int    Torso                   { get; set; } // int(11)
		[Column("textures"),                  NotNull] public string Textures                { get; set; } // mediumtext
		[Column("similar"),                   NotNull] public int    Similar                 { get; set; } // int(11)
		/// <summary>
		/// -1 - Не может быть вверхом, 0 - полностью закрыта, 1 - Полностью растегнута, 2 - растегнута на половину
		/// </summary>
		[Column("type"),                      NotNull] public short  Type                    { get; set; } // smallint(3)
		[Column("undershirt"),                NotNull] public int    Undershirt              { get; set; } // int(11)
		[Column("undershirt_buttoned"),       NotNull] public int    UndershirtButtoned      { get; set; } // int(11)
		[Column("undershirt_torso"),          NotNull] public int    UndershirtTorso         { get; set; } // int(11)
		[Column("undershirt_buttoned_torso"), NotNull] public int    UndershirtButtonedTorso { get; set; } // int(11)
		[Column("isClearLegs"),               NotNull] public bool   IsClearLegs             { get; set; } // tinyint(1)
		[Column("category"),                  NotNull] public string Category                { get; set; } // mediumtext
		[Column("price"),                     NotNull] public int    Price                   { get; set; } // int(11)
		[Column("donate"),                    NotNull] public int    Donate                  { get; set; } // int(11)
	}

	[Table("clothes_male_torsos")]
	public partial class ClothesMaleTorsos
	{
		[Column("id"),         PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull             ] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull             ] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull             ] public string Textures   { get; set; } // text
		[Column("price"),      NotNull             ] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull             ] public int    Donate     { get; set; } // int(11)
		[Column("torso"),      NotNull             ] public string Torso      { get; set; } // text
	}

	[Table("clothes_male_watches")]
	public partial class ClothesMaleWatches
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("category"),   NotNull] public string Category   { get; set; } // text
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
	}

	[Table("clothes_masks")]
	public partial class ClothesMasks
	{
		[Column("id"),         NotNull] public int    Id         { get; set; } // int(11)
		[Column("variation"),  NotNull] public int    Variation  { get; set; } // int(11)
		[Column("cvariation"), NotNull] public int    Cvariation { get; set; } // int(11)
		[Column("textures"),   NotNull] public string Textures   { get; set; } // text
		[Column("isHair"),     NotNull] public bool   IsHair     { get; set; } // tinyint(1)
		[Column("isHat"),      NotNull] public bool   IsHat      { get; set; } // tinyint(1)
		[Column("isGlasses"),  NotNull] public bool   IsGlasses  { get; set; } // tinyint(1)
		[Column("category"),   NotNull] public string Category   { get; set; } // mediumtext
		[Column("can_buy"),    NotNull] public bool   CanBuy     { get; set; } // tinyint(1)
		[Column("price"),      NotNull] public int    Price      { get; set; } // int(11)
		[Column("donate"),     NotNull] public int    Donate     { get; set; } // int(11)
		[Column("gender"),     NotNull] public sbyte  Gender     { get; set; } // tinyint(2)
	}

	[Table("everydayaward")]
	public partial class Everydayawards
	{
		[Column("autoId"), PrimaryKey, Identity] public int    AutoId { get; set; } // int(11)
		[Column("day"),    NotNull             ] public int    Day    { get; set; } // int(11)
		[Column("type"),   NotNull             ] public int    Type   { get; set; } // int(11)
		[Column("desc"),   NotNull             ] public string Desc   { get; set; } // varchar(26)
		[Column("count"),  NotNull             ] public int    Count  { get; set; } // int(11)
		[Column("itemId"), NotNull             ] public int    ItemId { get; set; } // int(11)
		[Column("data"),   NotNull             ] public string Data   { get; set; } // varchar(50)
		[Column("pngUrl"), NotNull             ] public string PngUrl { get; set; } // varchar(86)
		[Column("active"), NotNull             ] public bool   Active { get; set; } // tinyint(1)
	}

	[Table("ores")]
	public partial class Ores
	{
		[Column("index"),  PrimaryKey, NotNull] public int Index  { get; set; } // int(11)
		[Column("price"),              NotNull] public int Price  { get; set; } // int(11)
		[Column("itemId"),             NotNull] public int ItemId { get; set; } // int(11)
	}

	[Table("roulette")]
	public partial class Roulettes
	{
		[Column("autoId"),        PrimaryKey,  Identity] public int    AutoId        { get; set; } // int(11)
		[Column("caseId"),           Nullable          ] public int?   CaseId        { get; set; } // int(11)
		[Column("id"),               Nullable          ] public int?   Id            { get; set; } // int(11)
		[Column("name"),             Nullable          ] public string Name          { get; set; } // varchar(50)
		[Column("desc"),             Nullable          ] public string Desc          { get; set; } // varchar(150)
		[Column("image"),            Nullable          ] public string Image         { get; set; } // varchar(150)
		[Column("valueMin"),         Nullable          ] public int?   ValueMin      { get; set; } // int(11)
		[Column("valueMax"),         Nullable          ] public int?   ValueMax      { get; set; } // int(11)
		[Column("returnRB"),         Nullable          ] public int?   ReturnRB      { get; set; } // int(11)
		[Column("percent"),          Nullable          ] public int?   Percent       { get; set; } // int(11)
		[Column("color"),            Nullable          ] public int?   Color         { get; set; } // int(11)
		[Column("isChatMessage"), NotNull              ] public bool   IsChatMessage { get; set; } // tinyint(1)
		[Column("isHudMessage"),  NotNull              ] public bool   IsHudMessage  { get; set; } // tinyint(1)
		[Column("itemId"),        NotNull              ] public short  ItemId        { get; set; } // smallint(6)
		[Column("itemData"),      NotNull              ] public string ItemData      { get; set; } // varchar(50)
	}

	[Table("systemstate")]
	public partial class Systemstates
	{
		[Column("name"),   PrimaryKey, NotNull] public string Name   { get; set; } // varchar(50)
		[Column("toggle"),             NotNull] public bool   Toggle { get; set; } // tinyint(1)
	}

	[Table("tattoo_head")]
	public partial class TattooHeads
	{
		[Column("id"), PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column(),     NotNull             ] public string Name       { get; set; } // varchar(50)
		[Column(),     NotNull             ] public string Dictionary { get; set; } // varchar(50)
		[Column(),     NotNull             ] public string MaleHash   { get; set; } // varchar(50)
		[Column(),     NotNull             ] public string FemaleHash { get; set; } // varchar(50)
		/// <summary>
		/// Слоты совпадения что бы удалять существующие совпадения
		/// </summary>
		[Column(),     NotNull             ] public string Slots      { get; set; } // varchar(50)
		[Column(),     NotNull             ] public int    Price      { get; set; } // int(11)
		[Column(),     NotNull             ] public int    Donate     { get; set; } // int(11)
	}

	[Table("tattoo_leftarm")]
	public partial class TattooLeftarms
	{
		[Column("id"), PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column(),     NotNull             ] public string Name       { get; set; } // varchar(50)
		[Column(),     NotNull             ] public string Dictionary { get; set; } // varchar(50)
		[Column(),     NotNull             ] public string MaleHash   { get; set; } // varchar(50)
		[Column(),     NotNull             ] public string FemaleHash { get; set; } // varchar(50)
		/// <summary>
		/// Слоты совпадения что бы удалять существующие совпадения
		/// </summary>
		[Column(),     NotNull             ] public string Slots      { get; set; } // varchar(50)
		[Column(),     NotNull             ] public int    Price      { get; set; } // int(11)
		[Column(),     NotNull             ] public int    Donate     { get; set; } // int(11)
	}

	[Table("tattoo_leftleg")]
	public partial class TattooLeftlegs
	{
		[Column("id"), PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column(),     NotNull             ] public string Name       { get; set; } // varchar(50)
		[Column(),     NotNull             ] public string Dictionary { get; set; } // varchar(50)
		[Column(),     NotNull             ] public string MaleHash   { get; set; } // varchar(50)
		[Column(),     NotNull             ] public string FemaleHash { get; set; } // varchar(50)
		/// <summary>
		/// Слоты совпадения что бы удалять существующие совпадения
		/// </summary>
		[Column(),     NotNull             ] public string Slots      { get; set; } // varchar(50)
		[Column(),     NotNull             ] public int    Price      { get; set; } // int(11)
		[Column(),     NotNull             ] public int    Donate     { get; set; } // int(11)
	}

	[Table("tattoo_rightarm")]
	public partial class TattooRightarms
	{
		[Column("id"), PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column(),     NotNull             ] public string Name       { get; set; } // varchar(50)
		[Column(),     NotNull             ] public string Dictionary { get; set; } // varchar(50)
		[Column(),     NotNull             ] public string MaleHash   { get; set; } // varchar(50)
		[Column(),     NotNull             ] public string FemaleHash { get; set; } // varchar(50)
		/// <summary>
		/// Слоты совпадения что бы удалять существующие совпадения
		/// </summary>
		[Column(),     NotNull             ] public string Slots      { get; set; } // varchar(50)
		[Column(),     NotNull             ] public int    Price      { get; set; } // int(11)
		[Column(),     NotNull             ] public int    Donate     { get; set; } // int(11)
	}

	[Table("tattoo_rightleg")]
	public partial class TattooRightlegs
	{
		[Column("id"), PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column(),     NotNull             ] public string Name       { get; set; } // varchar(50)
		[Column(),     NotNull             ] public string Dictionary { get; set; } // varchar(50)
		[Column(),     NotNull             ] public string MaleHash   { get; set; } // varchar(50)
		[Column(),     NotNull             ] public string FemaleHash { get; set; } // varchar(50)
		/// <summary>
		/// Слоты совпадения что бы удалять существующие совпадения
		/// </summary>
		[Column(),     NotNull             ] public string Slots      { get; set; } // varchar(50)
		[Column(),     NotNull             ] public int    Price      { get; set; } // int(11)
		[Column(),     NotNull             ] public int    Donate     { get; set; } // int(11)
	}

	[Table("tattoo_torso")]
	public partial class TattooTorsoes
	{
		[Column("id"), PrimaryKey, Identity] public int    Id         { get; set; } // int(11)
		[Column(),     NotNull             ] public string Name       { get; set; } // varchar(50)
		[Column(),     NotNull             ] public string Dictionary { get; set; } // varchar(50)
		[Column(),     NotNull             ] public string MaleHash   { get; set; } // varchar(50)
		[Column(),     NotNull             ] public string FemaleHash { get; set; } // varchar(50)
		/// <summary>
		/// Слоты совпадения что бы удалять существующие совпадения
		/// </summary>
		[Column(),     NotNull             ] public string Slots      { get; set; } // varchar(50)
		[Column(),     NotNull             ] public int    Price      { get; set; } // int(11)
		[Column(),     NotNull             ] public int    Donate     { get; set; } // int(11)
	}

	public static partial class TableExtensions
	{
		public static BarberFemaleBeards Find(this ITable<BarberFemaleBeards> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static BarberFemaleBodies Find(this ITable<BarberFemaleBodies> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static BarberFemaleEyebrows Find(this ITable<BarberFemaleEyebrows> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static BarberFemaleEyes Find(this ITable<BarberFemaleEyes> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static BarberFemaleHair Find(this ITable<BarberFemaleHair> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static BarberFemaleLips Find(this ITable<BarberFemaleLips> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static BarberFemaleMakeups Find(this ITable<BarberFemaleMakeups> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static BarberFemalePalettes Find(this ITable<BarberFemalePalettes> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static BarberMaleBeards Find(this ITable<BarberMaleBeards> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static BarberMaleBodies Find(this ITable<BarberMaleBodies> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static BarberMaleEyebrows Find(this ITable<BarberMaleEyebrows> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static BarberMaleEyes Find(this ITable<BarberMaleEyes> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static BarberMaleHair Find(this ITable<BarberMaleHair> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static BarberMaleLips Find(this ITable<BarberMaleLips> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static BarberMaleMakeups Find(this ITable<BarberMaleMakeups> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static BarberMalePalettes Find(this ITable<BarberMalePalettes> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static BusProducts Find(this ITable<BusProducts> table, string Name)
		{
			return table.FirstOrDefault(t =>
				t.Name == Name);
		}

		public static ClothesFemaleTorsos Find(this ITable<ClothesFemaleTorsos> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static ClothesMaleTorsos Find(this ITable<ClothesMaleTorsos> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Everydayawards Find(this ITable<Everydayawards> table, int AutoId)
		{
			return table.FirstOrDefault(t =>
				t.AutoId == AutoId);
		}

		public static Ores Find(this ITable<Ores> table, int Index)
		{
			return table.FirstOrDefault(t =>
				t.Index == Index);
		}

		public static Roulettes Find(this ITable<Roulettes> table, int AutoId)
		{
			return table.FirstOrDefault(t =>
				t.AutoId == AutoId);
		}

		public static Systemstates Find(this ITable<Systemstates> table, string Name)
		{
			return table.FirstOrDefault(t =>
				t.Name == Name);
		}

		public static TattooHeads Find(this ITable<TattooHeads> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TattooLeftarms Find(this ITable<TattooLeftarms> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TattooLeftlegs Find(this ITable<TattooLeftlegs> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TattooRightarms Find(this ITable<TattooRightarms> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TattooRightlegs Find(this ITable<TattooRightlegs> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TattooTorsoes Find(this ITable<TattooTorsoes> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}

#pragma warning restore 1591
