export const FractionRankToAccess = {
    "Gov": 1,
    "TakeGuns": 2,
    "Warg": 3,
    "Ems": 4,
    "OpenWeaponStock": 5,
    "OpenStock": 6,
    "SetRank": 7,
    "Invite": 8,
    "UnInvite": 9,
    "Ticket": 10,
    "Arrest": 11,
    "Rfp": 12,
    "Follow": 13,
    "Su": 14,
    "InCar": 15,
    "Pull": 16,
    "TakeGunLic": 17,
    "TakeHelLic": 18,
    "TakePlaneLic": 19,
    "GiveGunLic": 20,
    "StealGuns": 21,
    "Pocket": 22,
    "GivePmLic": 23,
    "GiveMedLic": 24,
    "Medkit": 25,
    "Heal": 26,
    "Dep": 27,
    "TakeMats": 28,
    "TakeDrugs": 29,
    "TakeMoney": 30,
    "TakeMedkits": 31,
    "TakeStock": 32,
    "Capture": 33,
    "BuyDrugs": 34,
    "Delad": 35,
    "BizWar": 36,
    "Cuff": 37,
    "SetVehicleRank": 38,
    "DoorControl": 39,

    "TableWall": 40,
    "EditAllTabletWall": 41,
    "OrgTuning": 42,
    "OrgBuyCars": 43,
    "OrgSellCar": 44,
    "OrgUpgrate": 45,
    "OrgCrime": 46,

    "Logs": 47,
    "Reprimand": 48,
    "Dron": 49,
    "Ads": 50,
    
    "CaptureJoin": 51,
    "BizwarJoin": 52,

    "VehicleTicket": 53,
    "StartLiveStream": 62,

}

export const FractionRankToAccessName = {
    "Gov": "Гос. волна",
    "TakeGuns": "Изъятие оружия",
    "Warg": "Режим ЧП",
    "Ems": "Приняие вызова",
    "OpenWeaponStock": "Открывать склад оружия",
    "OpenStock": "Управление складом",
    "SetRank": "Настройки рангов",
    "Invite": "Приглашение во фракцию",
    "UnInvite": "Увольнение из фракции",
    "Ticket": "Выписывание штрафа",
    "Arrest": "Арест человека",
    "Rfp": "Освобождение из КПЗ",
    "Follow": "Ведение за собой",
    "Su": "Выдача розыска",
    "InCar": "Запихивание в машину",
    "Pull": "Вытаскивание из машины",
    "TakeGunLic": "Изъятие лицензии на оружие",
    "TakeHelLic": "Изъятие лицензии на вертолёт",
    "TakePlaneLic": "Изъятие лицензии на самолёт",
    "GiveGunLic": "Выдача лицензии на оружие",
    "StealGuns": "Кража оружия",
    "Pocket": "Обыск карманов",
    "GivePmLic": "Выдача лицензии парамедика",
    "GiveMedLic": "Выдача медицинской лицензии",
    "Medkit": "Продажа аптечек",
    "Heal": "Лечение человека",
    "Dep": "Волна департамента",
    "TakeMats": "Взятие материалов",
    "TakeDrugs": "Взятие наркотиков",
    "TakeMoney": "Взятие денег",
    "TakeMedkits": "Взятие аптечек",
    "TakeStock": "Взятие со склада",
    "Capture": "Забив капта",
    "BuyDrugs": "Покупка наркотиков",
    "Delad": "Удаление объявлений",
    "BizWar": "Забив бизвара",
    "Cuff": "Использование наручников и стяжек",
    "SetVehicleRank": "Изменение рангов т/с",
    "DoorControl": "Управление дверьми",
    "StartLiveStream":"Доступ к эфирам",
    "TableWall": "Публикация объявлений в планшете",
    "EditAllTabletWall": "Управление объявлениями в планшете",
    "OrgTuning": "Тюнинг транспорта",
    "OrgBuyCars": "Покупка транспорта",
    "OrgSellCar": "Продажа транспорта",
    "OrgUpgrate": "Покупка улучшений",
    "OrgCrime": "Криминальные действия",

    "Logs": "Доступ к логам",
    "Reprimand": "Выдача выговоров",

    "Dron": "Управление дроном",
    "Ads": "Доступ к объявлениям",
    
    "CaptureJoin": "Участие в капте",
    "BizwarJoin": "Участие в бизваре",

    "VehicleTicket": "Выписывать штрафы на т/с"
}