using System.Collections.Generic;
using GTANetworkAPI;
using NeptuneEvo.Handles;
using NeptuneEvo.VehicleModel.Models;
using NeptuneEvo.Chars;
using Redage.SDK;
using System;

namespace NeptuneEvo.VehicleModel
{
    class vMain : Script
    {
		private static readonly nLog Log = new nLog("VehicleModel.Main");

		public static readonly Dictionary<uint, VehicleInfo> VehicleData = new Dictionary<uint, VehicleInfo>()
        {
			{ NAPI.Util.GetHashKey("Faggio2"), new VehicleInfo("Motoroom", 3, 250)},
			{ NAPI.Util.GetHashKey("Verus"), new VehicleInfo("Motoroom", 5, 17500)},
			{ NAPI.Util.GetHashKey("Sanchez2"), new VehicleInfo("Motoroom", 5, 1750)},
			{ NAPI.Util.GetHashKey("Enduro"), new VehicleInfo("Motoroom", 5, 2000)},
			{ NAPI.Util.GetHashKey("PCJ"), new VehicleInfo("Motoroom", 5, 3250)},
			{ NAPI.Util.GetHashKey("Hexer"), new VehicleInfo("Motoroom", 5, 3500)},
			{ NAPI.Util.GetHashKey("Lectro"), new VehicleInfo("Motoroom", 5, 3750)},
			{ NAPI.Util.GetHashKey("Nemesis"), new VehicleInfo("Motoroom", 5, 3750)},
			{ NAPI.Util.GetHashKey("Hakuchou"), new VehicleInfo("Motoroom", 5, 4250)},
			{ NAPI.Util.GetHashKey("Ruffian"), new VehicleInfo("Motoroom", 5, 4750)},
			{ NAPI.Util.GetHashKey("Bmx"), new VehicleInfo("Motoroom", 0, 800)},
			{ NAPI.Util.GetHashKey("Scorcher"), new VehicleInfo("Motoroom", 0, 1200)},
			{ NAPI.Util.GetHashKey("BF400"), new VehicleInfo("Motoroom", 5, 5000)},
			{ NAPI.Util.GetHashKey("CarbonRS"), new VehicleInfo("Motoroom", 5, 5750)},
			{ NAPI.Util.GetHashKey("Bati"), new VehicleInfo("Motoroom", 5, 7000)},
			{ NAPI.Util.GetHashKey("Double"), new VehicleInfo("Motoroom", 5, 7500)},
			{ NAPI.Util.GetHashKey("Diablous"), new VehicleInfo("Motoroom", 5, 10000)},
			{ NAPI.Util.GetHashKey("Cliffhanger"), new VehicleInfo("Motoroom", 5, 11250)},
			{ NAPI.Util.GetHashKey("Akuma"), new VehicleInfo("Motoroom", 5, 13750)},
			{ NAPI.Util.GetHashKey("Thrust"), new VehicleInfo("Motoroom", 5, 16500)},
			{ NAPI.Util.GetHashKey("Nightblade"), new VehicleInfo("Motoroom", 5, 6000)},
			{ NAPI.Util.GetHashKey("Vindicator"), new VehicleInfo("Motoroom", 6, 8500)},
			{ NAPI.Util.GetHashKey("Ratbike"), new VehicleInfo("Motoroom", 5, 4500)},
			{ NAPI.Util.GetHashKey("Blazer"), new VehicleInfo("Motoroom", 7, 5200)},
			{ NAPI.Util.GetHashKey("Gargoyle"), new VehicleInfo("Motoroom", 5, 6800)},
			{ NAPI.Util.GetHashKey("Sanctus"), new VehicleInfo("Motoroom", 5, 500000)},
			{ NAPI.Util.GetHashKey("Bagger"), new VehicleInfo("Motoroom", 6, 2200)},
			{ NAPI.Util.GetHashKey("Diablous2"), new VehicleInfo("Motoroom", 5, 5600)},
			{ NAPI.Util.GetHashKey("Sovereign"), new VehicleInfo("Motoroom", 6, 2100)},
			{ NAPI.Util.GetHashKey("Avarus"), new VehicleInfo("Motoroom", 5, 4800)},
			{ NAPI.Util.GetHashKey("Bati2"), new VehicleInfo("Motoroom", 5, 7000)},
			{ NAPI.Util.GetHashKey("Daemon"), new VehicleInfo("Motoroom", 5, 4800)},
			{ NAPI.Util.GetHashKey("Daemon2"), new VehicleInfo("Motoroom", 5, 4700)},
			{ NAPI.Util.GetHashKey("Defiler"), new VehicleInfo("Motoroom", 5, 6000)},
			{ NAPI.Util.GetHashKey("Vortex"), new VehicleInfo("Motoroom", 5, 5800)},
			{ NAPI.Util.GetHashKey("Vader"), new VehicleInfo("Motoroom", 5, 4950)},
			{ NAPI.Util.GetHashKey("Esskey"), new VehicleInfo("Motoroom", 5, 4000)},
			{ NAPI.Util.GetHashKey("Faggio"), new VehicleInfo("Motoroom", 3, 260)},
			{ NAPI.Util.GetHashKey("Faggio3"), new VehicleInfo("Motoroom", 3, 300)},
			{ NAPI.Util.GetHashKey("Manchez"), new VehicleInfo("Motoroom", 5, 1900)},
			{ NAPI.Util.GetHashKey("Wolfsbane"), new VehicleInfo("Motoroom", 5, 4800)},
			{ NAPI.Util.GetHashKey("Zombiea"), new VehicleInfo("Motoroom", 5, 5000)},
			{ NAPI.Util.GetHashKey("Zombieb"), new VehicleInfo("Motoroom", 5, 5100)},
			{ NAPI.Util.GetHashKey("Blazer4"), new VehicleInfo("Motoroom", 7, 5800)},
			{ NAPI.Util.GetHashKey("Deathbike"), new VehicleInfo("Motoroom", 5, 14000)},
			{ NAPI.Util.GetHashKey("Fcr"), new VehicleInfo("Motoroom", 5, 6000)},
			{ NAPI.Util.GetHashKey("Fcr2"), new VehicleInfo("Motoroom", 5, 7000)},
			{ NAPI.Util.GetHashKey("Hakuchou2"), new VehicleInfo("Motoroom", 5, 18000)},
			{ NAPI.Util.GetHashKey("Innovation"), new VehicleInfo("Motoroom", 5, 25000)},
			{ NAPI.Util.GetHashKey("Stryder"), new VehicleInfo("Motoroom", 7, 20000)},
			{ NAPI.Util.GetHashKey("Fixter"), new VehicleInfo("Motoroom", 0, 1000)},
			{ NAPI.Util.GetHashKey("Cruiser"), new VehicleInfo("Motoroom", 0, 1200)},
			{ NAPI.Util.GetHashKey("Tribike"), new VehicleInfo("Motoroom", 0, 1500)},
			{ NAPI.Util.GetHashKey("Tribike2"), new VehicleInfo("Motoroom", 0, 1500)},
			{ NAPI.Util.GetHashKey("Tribike3"), new VehicleInfo("Motoroom", 0, 1500)},
			{ NAPI.Util.GetHashKey("Blazer3"), new VehicleInfo("Motoroom", 7, 8000)},
			{ NAPI.Util.GetHashKey("Tornado3"), new VehicleInfo("Low Autoroom", 15, 750)},
			{ NAPI.Util.GetHashKey("Tornado4"), new VehicleInfo("Low Autoroom", 15, 800)},
			{ NAPI.Util.GetHashKey("Emperor2"), new VehicleInfo("Low Autoroom", 20, 800)},
			{ NAPI.Util.GetHashKey("Voodoo2"), new VehicleInfo("Low Autoroom", 15, 825)},
			{ NAPI.Util.GetHashKey("Regina"), new VehicleInfo("Low Autoroom", 30, 850)},
			{ NAPI.Util.GetHashKey("Ingot"), new VehicleInfo("Low Autoroom", 30, 875)},
			{ NAPI.Util.GetHashKey("Emperor"), new VehicleInfo("Low Autoroom", 20, 2000)},
			{ NAPI.Util.GetHashKey("Picador"), new VehicleInfo("Low Autoroom", 25, 2250)},
			{ NAPI.Util.GetHashKey("Minivan"), new VehicleInfo("Low Autoroom", 35, 2000)},
			{ NAPI.Util.GetHashKey("Blista2"), new VehicleInfo("Low Autoroom", 15, 2250)},
			{ NAPI.Util.GetHashKey("Manana"), new VehicleInfo("Low Autoroom", 15, 2250)},
			{ NAPI.Util.GetHashKey("Dilettante"), new VehicleInfo("Low Autoroom", 25, 2500)},
			{ NAPI.Util.GetHashKey("Asea"), new VehicleInfo("Low Autoroom", 25, 2500)},
			{ NAPI.Util.GetHashKey("Glendale"), new VehicleInfo("Low Autoroom", 25, 3250)},
			{ NAPI.Util.GetHashKey("Voodoo"), new VehicleInfo("Low Autoroom", 15, 2500)},
			{ NAPI.Util.GetHashKey("Surge"), new VehicleInfo("Low Autoroom", 25, 3250)},
			{ NAPI.Util.GetHashKey("Primo"), new VehicleInfo("Low Autoroom", 25, 3370)},
			{ NAPI.Util.GetHashKey("Stanier"), new VehicleInfo("Low Autoroom", 25, 3500)},
			{ NAPI.Util.GetHashKey("Stratum"), new VehicleInfo("Low Autoroom", 30, 3750)},
			{ NAPI.Util.GetHashKey("Tampa"), new VehicleInfo("Low Autoroom", 15, 3875)},
			{ NAPI.Util.GetHashKey("Prairie"), new VehicleInfo("Low Autoroom", 15, 3950)},
			{ NAPI.Util.GetHashKey("Radi"), new VehicleInfo("Low Autoroom", 35, 3900)},
			{ NAPI.Util.GetHashKey("Blista"), new VehicleInfo("Low Autoroom", 15, 4150)},
			{ NAPI.Util.GetHashKey("Stalion"), new VehicleInfo("Low Autoroom", 15, 4250)},
			{ NAPI.Util.GetHashKey("Asterope"), new VehicleInfo("Low Autoroom", 25, 4700)},
			{ NAPI.Util.GetHashKey("Washington"), new VehicleInfo("Low Autoroom", 25, 4975)},
			{ NAPI.Util.GetHashKey("Premier"), new VehicleInfo("Low Autoroom", 25, 5000)},
			{ NAPI.Util.GetHashKey("Intruder"), new VehicleInfo("Low Autoroom", 25, 4500)},
			{ NAPI.Util.GetHashKey("Ruiner"), new VehicleInfo("Low Autoroom", 15, 5000)},
			{ NAPI.Util.GetHashKey("Oracle"), new VehicleInfo("Low Autoroom", 25, 5250)},
			{ NAPI.Util.GetHashKey("Phoenix"), new VehicleInfo("Low Autoroom", 15, 6250)},
			{ NAPI.Util.GetHashKey("Gauntlet"), new VehicleInfo("Low Autoroom", 15, 7000)},
			{ NAPI.Util.GetHashKey("Buffalo"), new VehicleInfo("Low Autoroom", 25, 7000)},
			{ NAPI.Util.GetHashKey("RancherXL"), new VehicleInfo("Low Autoroom", 45, 3750)},
			{ NAPI.Util.GetHashKey("Seminole"), new VehicleInfo("Low Autoroom", 35, 5000)},
			{ NAPI.Util.GetHashKey("Baller"), new VehicleInfo("Low Autoroom", 35, 12500)},
			{ NAPI.Util.GetHashKey("Landstalker"), new VehicleInfo("Low Autoroom", 35, 13750)},
			{ NAPI.Util.GetHashKey("Cavalcade"), new VehicleInfo("Low Autoroom", 35, 15000)},
			{ NAPI.Util.GetHashKey("BJXL"), new VehicleInfo("Low Autoroom", 35, 15250)},
			{ NAPI.Util.GetHashKey("Patriot"), new VehicleInfo("Low Autoroom", 35, 17500)},
			{ NAPI.Util.GetHashKey("Bison3"), new VehicleInfo("Low Autoroom", 35, 7500)},
			{ NAPI.Util.GetHashKey("Issi2"), new VehicleInfo("Low Autoroom", 15, 8500)},
			{ NAPI.Util.GetHashKey("Panto"), new VehicleInfo("Low Autoroom", 15, 4500)},
			{ NAPI.Util.GetHashKey("Rhapsody"), new VehicleInfo("Low Autoroom", 15, 1000)},
			{ NAPI.Util.GetHashKey("Buccaneer2"), new VehicleInfo("Low Autoroom", 15, 3600)},
			{ NAPI.Util.GetHashKey("Dukes"), new VehicleInfo("Low Autoroom", 15, 3800)},
			{ NAPI.Util.GetHashKey("Faction"), new VehicleInfo("Low Autoroom", 15, 3000)},
			{ NAPI.Util.GetHashKey("Faction2"), new VehicleInfo("Low Autoroom", 15, 3800)},
			{ NAPI.Util.GetHashKey("Hermes"), new VehicleInfo("Low Autoroom", 15, 1200)},
			{ NAPI.Util.GetHashKey("Moonbeam2"), new VehicleInfo("Low Autoroom", 45, 6400)},
			{ NAPI.Util.GetHashKey("Futo"), new VehicleInfo("Low Autoroom", 15, 6200)},
			{ NAPI.Util.GetHashKey("Blade"), new VehicleInfo("Low Autoroom", 15, 3400)},
			{ NAPI.Util.GetHashKey("Chino"), new VehicleInfo("Low Autoroom", 15, 2200)},
			{ NAPI.Util.GetHashKey("Chino2"), new VehicleInfo("Low Autoroom", 15, 3000)},
			{ NAPI.Util.GetHashKey("Gauntlet2"), new VehicleInfo("Low Autoroom", 15, 7000)},
			{ NAPI.Util.GetHashKey("Sabregt"), new VehicleInfo("Low Autoroom", 15, 6000)},
			{ NAPI.Util.GetHashKey("Sabregt2"), new VehicleInfo("Low Autoroom", 15, 6900)},
			{ NAPI.Util.GetHashKey("Stalion2"), new VehicleInfo("Low Autoroom", 15, 4250)},
			{ NAPI.Util.GetHashKey("Bfinjection"), new VehicleInfo("Low Autoroom", 15, 2300)},
			{ NAPI.Util.GetHashKey("Bodhi2"), new VehicleInfo("Low Autoroom", 40, 4000)},
			{ NAPI.Util.GetHashKey("Rebel"), new VehicleInfo("Low Autoroom", 40, 4900)},
			{ NAPI.Util.GetHashKey("Rebel2"), new VehicleInfo("Low Autoroom", 40, 5000)},
			{ NAPI.Util.GetHashKey("Primo2"), new VehicleInfo("Low Autoroom", 25, 4300)},
			{ NAPI.Util.GetHashKey("Warrener"), new VehicleInfo("Low Autoroom", 25, 3700)},
			{ NAPI.Util.GetHashKey("Buffalo2"), new VehicleInfo("Low Autoroom", 25, 8200)},
			{ NAPI.Util.GetHashKey("Slamvan"), new VehicleInfo("Low Autoroom", 40, 4500)},
			{ NAPI.Util.GetHashKey("Virgo"), new VehicleInfo("Low Autoroom", 15, 2000)},
			{ NAPI.Util.GetHashKey("Virgo2"), new VehicleInfo("Low Autoroom", 15, 2400)},
			{ NAPI.Util.GetHashKey("Virgo3"), new VehicleInfo("Low Autoroom", 15, 2410)},
			{ NAPI.Util.GetHashKey("Blista3"), new VehicleInfo("Low Autoroom", 15, 4300)},
			{ NAPI.Util.GetHashKey("Buffalo3"), new VehicleInfo("Low Autoroom", 25, 8200)},
			{ NAPI.Util.GetHashKey("Peyote"), new VehicleInfo("Low Autoroom", 15, 2900)},
			{ NAPI.Util.GetHashKey("Retinue"), new VehicleInfo("Low Autoroom", 25, 5600)},
			{ NAPI.Util.GetHashKey("Savestra"), new VehicleInfo("Low Autoroom", 25, 5700)},
			{ NAPI.Util.GetHashKey("Tornado"), new VehicleInfo("Low Autoroom", 15, 700)},
			{ NAPI.Util.GetHashKey("Tornado2"), new VehicleInfo("Low Autoroom", 15, 740)},
			{ NAPI.Util.GetHashKey("Brioso2"), new VehicleInfo("Low Autoroom", 15, 3500)},
			{ NAPI.Util.GetHashKey("Weevil"), new VehicleInfo("Low Autoroom", 15, 4000)},
			{ NAPI.Util.GetHashKey("Tornado5"), new VehicleInfo("Low Autoroom", 15, 950)},
			{ NAPI.Util.GetHashKey("Brioso"), new VehicleInfo("Low Autoroom", 15, 4800)},
			{ NAPI.Util.GetHashKey("Issi3"), new VehicleInfo("Low Autoroom", 15, 3200)},
			{ NAPI.Util.GetHashKey("Tulip"), new VehicleInfo("Low Autoroom", 15, 7500)},
			{ NAPI.Util.GetHashKey("Vamos"), new VehicleInfo("Low Autoroom", 15, 7800)},
			{ NAPI.Util.GetHashKey("Hellion"), new VehicleInfo("Low Autoroom", 35, 16000)},
			{ NAPI.Util.GetHashKey("Nebula"), new VehicleInfo("Low Autoroom", 25, 3700)},
			{ NAPI.Util.GetHashKey("Cheburek"), new VehicleInfo("Low Autoroom", 25, 25000)},
			{ NAPI.Util.GetHashKey("Zion3"), new VehicleInfo("Low Autoroom", 15, 19000)},
			{ NAPI.Util.GetHashKey("Gauntlet3"), new VehicleInfo("Low Autoroom", 15, 9500)},
			{ NAPI.Util.GetHashKey("Imperator"), new VehicleInfo("Low Autoroom", 15, 9000)},
			{ NAPI.Util.GetHashKey("Habanero"), new VehicleInfo("Low Autoroom", 30, 6100)},
			{ NAPI.Util.GetHashKey("Ellie"), new VehicleInfo("Low Autoroom", 15, 11000)},
			{ NAPI.Util.GetHashKey("Retinue2"), new VehicleInfo("Low Autoroom", 25, 5500)},
			{ NAPI.Util.GetHashKey("Yosemite2"), new VehicleInfo("Low Autoroom", 40, 4600)},
			{ NAPI.Util.GetHashKey("Asbo"), new VehicleInfo("Low Autoroom", 15, 4800)},
			{ NAPI.Util.GetHashKey("Kanjo"), new VehicleInfo("Low Autoroom", 15, 5200)},
			{ NAPI.Util.GetHashKey("Clique"), new VehicleInfo("Low Autoroom", 15, 2000)},
			{ NAPI.Util.GetHashKey("Ratloader2"), new VehicleInfo("Low Autoroom", 40, 8000)},
			{ NAPI.Util.GetHashKey("Yosemite"), new VehicleInfo("Low Autoroom", 40, 2500)},
			{ NAPI.Util.GetHashKey("Dloader"), new VehicleInfo("Low Autoroom", 45, 3000)},
			{ NAPI.Util.GetHashKey("Dynasty"), new VehicleInfo("Low Autoroom", 25, 2000)},
			{ NAPI.Util.GetHashKey("Fagaloa"), new VehicleInfo("Low Autoroom", 30, 1500)},
			{ NAPI.Util.GetHashKey("Club"), new VehicleInfo("Low Autoroom", 25, 5400)},
			{ NAPI.Util.GetHashKey("Dukes3"), new VehicleInfo("Low Autoroom", 15, 5800)},
			{ NAPI.Util.GetHashKey("Glendale2"), new VehicleInfo("Low Autoroom", 25, 4250)},
			{ NAPI.Util.GetHashKey("Peyote3"), new VehicleInfo("Low Autoroom", 15, 5900)},
			{ NAPI.Util.GetHashKey("Manana2"), new VehicleInfo("Low Autoroom", 15, 2460)},

			{ NAPI.Util.GetHashKey("warrener2"), new VehicleInfo("Low Autoroom", 35, 4400)},
			{ NAPI.Util.GetHashKey("previon"), new VehicleInfo("Low Autoroom", 15, 6800)},
			{ NAPI.Util.GetHashKey("remus"), new VehicleInfo("Low Autoroom", 15, 7400)},
			{ NAPI.Util.GetHashKey("futo2"), new VehicleInfo("Low Autoroom", 15, 7600)},
			{ NAPI.Util.GetHashKey("dominator8"), new VehicleInfo("Low Autoroom", 15, 14000)},

			{ NAPI.Util.GetHashKey("Sultan"), new VehicleInfo("Premium Autoroom", 25, 11250)},
			{ NAPI.Util.GetHashKey("SultanRS"), new VehicleInfo("Premium Autoroom", 15, 80000)},
			{ NAPI.Util.GetHashKey("Kuruma"), new VehicleInfo("Premium Autoroom", 25, 40000)},
			{ NAPI.Util.GetHashKey("Fugitive"), new VehicleInfo("Premium Autoroom", 25, 9250)},
			{ NAPI.Util.GetHashKey("Tailgater"), new VehicleInfo("Premium Autoroom", 25, 9500)},
			{ NAPI.Util.GetHashKey("Sentinel"), new VehicleInfo("Premium Autoroom", 15, 11250)},
			{ NAPI.Util.GetHashKey("F620"), new VehicleInfo("Premium Autoroom", 15, 18250)},
			{ NAPI.Util.GetHashKey("Schwarzer"), new VehicleInfo("Premium Autoroom", 25, 18750)},
			{ NAPI.Util.GetHashKey("Exemplar"), new VehicleInfo("Premium Autoroom", 25, 20750)},
			{ NAPI.Util.GetHashKey("Felon"), new VehicleInfo("Premium Autoroom", 25, 20000)},
			{ NAPI.Util.GetHashKey("Schafter2"), new VehicleInfo("Premium Autoroom", 25, 22500)},
			{ NAPI.Util.GetHashKey("Jackal"), new VehicleInfo("Premium Autoroom", 25, 25000)},
			{ NAPI.Util.GetHashKey("Oracle2"), new VehicleInfo("Premium Autoroom", 25, 30000)},
			{ NAPI.Util.GetHashKey("Surano"), new VehicleInfo("Premium Autoroom", 15, 32550)},
			{ NAPI.Util.GetHashKey("Zion"), new VehicleInfo("Premium Autoroom", 15, 37500)},
			{ NAPI.Util.GetHashKey("Dominator"), new VehicleInfo("Premium Autoroom", 15, 22500)},
			{ NAPI.Util.GetHashKey("FQ2"), new VehicleInfo("Premium Autoroom", 35, 26250)},
			{ NAPI.Util.GetHashKey("Gresley"), new VehicleInfo("Premium Autoroom", 35, 27500)},
			{ NAPI.Util.GetHashKey("Serrano"), new VehicleInfo("Premium Autoroom", 35, 32500)},
			{ NAPI.Util.GetHashKey("Dubsta"), new VehicleInfo("Premium Autoroom", 35, 33750)},
			{ NAPI.Util.GetHashKey("Rocoto"), new VehicleInfo("Premium Autoroom", 35, 37500)},
			{ NAPI.Util.GetHashKey("Cavalcade2"), new VehicleInfo("Premium Autoroom", 35, 40000)},
			{ NAPI.Util.GetHashKey("XLS"), new VehicleInfo("Premium Autoroom", 35, 40000)},
			{ NAPI.Util.GetHashKey("Baller2"), new VehicleInfo("MPremium Autoroom", 35, 45000)},
			{ NAPI.Util.GetHashKey("Elegy"), new VehicleInfo("Premium Autoroom", 15, 70000)},
			{ NAPI.Util.GetHashKey("Banshee"), new VehicleInfo("Premium Autoroom", 15, 67500)},
			{ NAPI.Util.GetHashKey("Massacro2"), new VehicleInfo("Premium Autoroom", 15, 59500)},
			{ NAPI.Util.GetHashKey("GP1"), new VehicleInfo("Premium Autoroom", 15, 62500)},
			{ NAPI.Util.GetHashKey("Revolter"), new VehicleInfo("Premium Autoroom", 25, 41000)},
			{ NAPI.Util.GetHashKey("Brawler"), new VehicleInfo("Premium Autoroom", 35, 26000)},
			{ NAPI.Util.GetHashKey("Sandking"), new VehicleInfo("Premium Autoroom", 45, 40000)},
			{ NAPI.Util.GetHashKey("Sandking2"), new VehicleInfo("Premium Autoroom", 45, 38000)},
			{ NAPI.Util.GetHashKey("Feltzer2"), new VehicleInfo("Premium Autoroom", 15, 60000)},
			{ NAPI.Util.GetHashKey("Massacro"), new VehicleInfo("Premium Autoroom", 15, 59500)},
			{ NAPI.Util.GetHashKey("Casco"), new VehicleInfo("Premium Autoroom", 15, 69000)},
			{ NAPI.Util.GetHashKey("Bifta"), new VehicleInfo("Premium Autoroom", 10, 18000)},
			{ NAPI.Util.GetHashKey("Cogcabrio"), new VehicleInfo("Premium Autoroom", 15, 21000)},
			{ NAPI.Util.GetHashKey("Dominator2"), new VehicleInfo("Premium Autoroom", 15, 37500)},
			{ NAPI.Util.GetHashKey("Nightshade"), new VehicleInfo("Premium Autoroom", 15, 53000)},
			{ NAPI.Util.GetHashKey("Contender"), new VehicleInfo("Premium Autoroom", 45, 70000)},
			{ NAPI.Util.GetHashKey("Cog55"), new VehicleInfo("Premium Autoroom", 25, 22000)},
			{ NAPI.Util.GetHashKey("Cognoscenti"), new VehicleInfo("Premium Autoroom", 25, 23500)},
			{ NAPI.Util.GetHashKey("Alpha"), new VehicleInfo("Premium Autoroom", 15, 54000)},
			{ NAPI.Util.GetHashKey("Furoregt"), new VehicleInfo("Premium Autoroom", 15, 52000)},
			{ NAPI.Util.GetHashKey("Lynx"), new VehicleInfo("Premium Autoroom", 15, 60000)},
			{ NAPI.Util.GetHashKey("Pariah"), new VehicleInfo("Premium Autoroom", 15, 74000)},
			{ NAPI.Util.GetHashKey("Tampa2"), new VehicleInfo("Premium Autoroom", 15, 76000)},
			{ NAPI.Util.GetHashKey("Tropos"), new VehicleInfo("Premium Autoroom", 15, 67000)},
			{ NAPI.Util.GetHashKey("Felon2"), new VehicleInfo("Premium Autoroom", 15, 20800)},
			{ NAPI.Util.GetHashKey("Sentinel2"), new VehicleInfo("Premium Autoroom", 15, 11500)},
			{ NAPI.Util.GetHashKey("Zion2"), new VehicleInfo("Premium Autoroom", 15, 32500)},
			{ NAPI.Util.GetHashKey("Fusilade"), new VehicleInfo("Premium Autoroom", 15, 19500)},
			{ NAPI.Util.GetHashKey("Penumbra"), new VehicleInfo("Premium Autoroom", 15, 32000)},
			{ NAPI.Util.GetHashKey("Rapidgt"), new VehicleInfo("Premium Autoroom", 15, 19000)},
			{ NAPI.Util.GetHashKey("Rapidgt2"), new VehicleInfo("Premium Autoroom", 15, 38500)},
			{ NAPI.Util.GetHashKey("Schafter3"), new VehicleInfo("Premium Autoroom", 25, 20500)},
			{ NAPI.Util.GetHashKey("Sentinel3"), new VehicleInfo("Premium Autoroom", 15, 17500)},
			{ NAPI.Util.GetHashKey("Voltic"), new VehicleInfo("Premium Autoroom", 15, 64000)},
			{ NAPI.Util.GetHashKey("Gauntlet4"), new VehicleInfo("Premium Autoroom", 15, 20000)},
			{ NAPI.Util.GetHashKey("Caracara2"), new VehicleInfo("Premium Autoroom", 45, 65000)},
			{ NAPI.Util.GetHashKey("Issi7"), new VehicleInfo("Premium Autoroom", 15, 13000)},
			{ NAPI.Util.GetHashKey("Schafter4"), new VehicleInfo("Premium Autoroom", 25, 21000)},
			{ NAPI.Util.GetHashKey("Novak"), new VehicleInfo("Premium Autoroom", 35, 44000)},
			{ NAPI.Util.GetHashKey("Z190"), new VehicleInfo("Premium Autoroom", 15, 63000)},
			{ NAPI.Util.GetHashKey("Gb200"), new VehicleInfo("Premium Autoroom", 15, 84000)},
			{ NAPI.Util.GetHashKey("Sultan2"), new VehicleInfo("Premium Autoroom", 25, 106000)},
			{ NAPI.Util.GetHashKey("Rebla"), new VehicleInfo("Premium Autoroom", 35, 55000)},
			{ NAPI.Util.GetHashKey("Komoda"), new VehicleInfo("Premium Autoroom", 25, 33000)},
			{ NAPI.Util.GetHashKey("Sugoi"), new VehicleInfo("Premium Autoroom", 25, 80000)},
			{ NAPI.Util.GetHashKey("Vstr"), new VehicleInfo("Premium Autoroom", 25, 85000)},
			{ NAPI.Util.GetHashKey("Penumbra2"), new VehicleInfo("Premium Autoroom", 15, 86000)},
			{ NAPI.Util.GetHashKey("Landstalker2"), new VehicleInfo("Premium Autoroom", 35, 52000)},
			{ NAPI.Util.GetHashKey("Yosemite3"), new VehicleInfo("Premium Autoroom", 35, 6000)},
			{ NAPI.Util.GetHashKey("Gauntlet5"), new VehicleInfo("Premium Autoroom", 15, 11000)},
			{ NAPI.Util.GetHashKey("Seminole2"), new VehicleInfo("Premium Autoroom", 35, 13400)},

			{ NAPI.Util.GetHashKey("tailgater2"), new VehicleInfo("Premium Autoroom", 25, 42000)},
			{ NAPI.Util.GetHashKey("cypher"), new VehicleInfo("Premium Autoroom", 15, 51000)},
			{ NAPI.Util.GetHashKey("zr350"), new VehicleInfo("Premium Autoroom", 15, 80000)},
			{ NAPI.Util.GetHashKey("calico"), new VehicleInfo("Premium Autoroom", 15, 90000)},
			{ NAPI.Util.GetHashKey("euros"), new VehicleInfo("Premium Autoroom", 15, 92000)},
			{ NAPI.Util.GetHashKey("dominator7"), new VehicleInfo("Premium Autoroom", 15, 98000)},
			{ NAPI.Util.GetHashKey("sultan3"), new VehicleInfo("Premium Autoroom", 15, 110000)},
			{ NAPI.Util.GetHashKey("datsun"), new VehicleInfo("Premium Autoroom", 15, 110000)},

			{ NAPI.Util.GetHashKey("Comet2"), new VehicleInfo("Luxor Autoroom", 15, 44200)},
			{ NAPI.Util.GetHashKey("Coquette"), new VehicleInfo("Luxor Autoroom", 15, 43200)},
			{ NAPI.Util.GetHashKey("Ninef"), new VehicleInfo("Luxor Autoroom", 15, 45500)},
			{ NAPI.Util.GetHashKey("Ninef2"), new VehicleInfo("Luxor Autoroom", 15, 46000)},
			{ NAPI.Util.GetHashKey("Jester"), new VehicleInfo("Luxor Autoroom", 15, 49000)},
			{ NAPI.Util.GetHashKey("Elegy2"), new VehicleInfo("Luxor Autoroom", 15, 38500)},
			{ NAPI.Util.GetHashKey("Deveste"), new VehicleInfo("Luxor Autoroom", 5, 475000)},
			{ NAPI.Util.GetHashKey("Infernus"), new VehicleInfo("Luxor Autoroom", 15, 46500)},
			{ NAPI.Util.GetHashKey("Carbonizzare"), new VehicleInfo("Luxor Autoroom", 10, 48500)},
			{ NAPI.Util.GetHashKey("Dubsta2"), new VehicleInfo("Luxor Autoroom", 35, 41000)},
			{ NAPI.Util.GetHashKey("Baller3"), new VehicleInfo("Luxor Autoroom", 35, 49000)},
			{ NAPI.Util.GetHashKey("Huntley"), new VehicleInfo("Luxor Autoroom", 35, 41000)},
			{ NAPI.Util.GetHashKey("Superd"), new VehicleInfo("Luxor Autoroom", 25, 70000)},
			{ NAPI.Util.GetHashKey("Windsor"), new VehicleInfo("Luxor Autoroom", 20, 65000)},
			{ NAPI.Util.GetHashKey("BestiaGTS"), new VehicleInfo("Luxor Autoroom", 15, 45200)},
			{ NAPI.Util.GetHashKey("Banshee2"), new VehicleInfo("Luxor Autoroom", 15, 74500)},
			{ NAPI.Util.GetHashKey("EntityXF"), new VehicleInfo("Luxor Autoroom", 15, 81000)},
			{ NAPI.Util.GetHashKey("Neon"), new VehicleInfo("Luxor Autoroom", 25, 89500)},
			{ NAPI.Util.GetHashKey("Jester2"), new VehicleInfo("Luxor Autoroom", 15, 81000)},
			{ NAPI.Util.GetHashKey("Turismor"), new VehicleInfo("Luxor Autoroom", 15, 120000)},
			{ NAPI.Util.GetHashKey("Penetrator"), new VehicleInfo("Luxor Autoroom", 15, 115000)},
			{ NAPI.Util.GetHashKey("Omnis"), new VehicleInfo("Luxor Autoroom", 15, 69500)},
			{ NAPI.Util.GetHashKey("Reaper"), new VehicleInfo("Luxor Autoroom", 15, 200000)},
			{ NAPI.Util.GetHashKey("Italigtb2"), new VehicleInfo("Luxor Autoroom", 15, 160000)},
			{ NAPI.Util.GetHashKey("Xa21"), new VehicleInfo("Luxor Autoroom", 15, 300000)},
			{ NAPI.Util.GetHashKey("Osiris"), new VehicleInfo("Luxor Autoroom", 15, 310000)},
			{ NAPI.Util.GetHashKey("Nero"), new VehicleInfo("Luxor Autoroom", 15, 400000)},
			{ NAPI.Util.GetHashKey("Zentorno"), new VehicleInfo("Luxor Autoroom", 15, 1000000)},
			{ NAPI.Util.GetHashKey("Infernus2"), new VehicleInfo("Luxor Autoroom", 15, 280000)},
			{ NAPI.Util.GetHashKey("Cheetah2"), new VehicleInfo("Luxor Autoroom", 15, 265000)},
			{ NAPI.Util.GetHashKey("Feltzer3"), new VehicleInfo("Luxor Autoroom", 15, 180000)},
			{ NAPI.Util.GetHashKey("Mamba"), new VehicleInfo("Luxor Autoroom", 15, 180000)},
			{ NAPI.Util.GetHashKey("Monroe"), new VehicleInfo("Luxor Autoroom", 15, 165000)},
			{ NAPI.Util.GetHashKey("Rapidgt3"), new VehicleInfo("Luxor Autoroom", 15, 140000)},
			{ NAPI.Util.GetHashKey("Swinger"), new VehicleInfo("Luxor Autoroom", 15, 160000)},
			{ NAPI.Util.GetHashKey("Torero"), new VehicleInfo("Luxor Autoroom", 15, 205000)},
			{ NAPI.Util.GetHashKey("Turismo2"), new VehicleInfo("Luxor Autoroom", 15, 270000)},
			{ NAPI.Util.GetHashKey("Viseris"), new VehicleInfo("Luxor Autoroom", 15, 245000)},
			{ NAPI.Util.GetHashKey("Coquette3"), new VehicleInfo("Luxor Autoroom", 15, 170000)},
			{ NAPI.Util.GetHashKey("Dubsta3"), new VehicleInfo("Luxor Autoroom", 45, 100000)},
			{ NAPI.Util.GetHashKey("Comet3"), new VehicleInfo("Luxor Autoroom", 15, 110000)},
			{ NAPI.Util.GetHashKey("Khamelion"), new VehicleInfo("Luxor Autoroom", 15, 80000)},
			{ NAPI.Util.GetHashKey("Seven70"), new VehicleInfo("Luxor Autoroom", 15, 115000)},
			{ NAPI.Util.GetHashKey("Specter"), new VehicleInfo("Luxor Autoroom", 15, 114000)},
			{ NAPI.Util.GetHashKey("Specter2"), new VehicleInfo("Luxor Autoroom", 15, 120000)},
			{ NAPI.Util.GetHashKey("Verlierer2"), new VehicleInfo("Luxor Autoroom", 15, 80000)},
			{ NAPI.Util.GetHashKey("Adder"), new VehicleInfo("Luxor Autoroom", 15, 360000)},
			{ NAPI.Util.GetHashKey("Bullet"), new VehicleInfo("Luxor Autoroom", 15, 195000)},
			{ NAPI.Util.GetHashKey("Cheetah"), new VehicleInfo("Luxor Autoroom", 15, 121000)},
			{ NAPI.Util.GetHashKey("Cyclone"), new VehicleInfo("Luxor Autoroom", 15, 125000)},
			{ NAPI.Util.GetHashKey("Fmj"), new VehicleInfo("Luxor Autoroom", 15, 365000)},
			{ NAPI.Util.GetHashKey("Pfister811"), new VehicleInfo("Luxor Autoroom", 15, 370000)},
			{ NAPI.Util.GetHashKey("Sc1"), new VehicleInfo("Luxor Autoroom", 15, 265000)},
			{ NAPI.Util.GetHashKey("T20"), new VehicleInfo("Luxor Autoroom", 15, 400000)},
			{ NAPI.Util.GetHashKey("Tempesta"), new VehicleInfo("Luxor Autoroom", 15, 195000)},
			{ NAPI.Util.GetHashKey("Vacca"), new VehicleInfo("Luxor Autoroom", 15, 160000)},
			{ NAPI.Util.GetHashKey("Vagner"), new VehicleInfo("Luxor Autoroom", 15, 320000)},
			{ NAPI.Util.GetHashKey("Visione"), new VehicleInfo("Luxor Autoroom", 15, 450000)},
			{ NAPI.Util.GetHashKey("Baller4"), new VehicleInfo("Luxor Autoroom", 35, 49500)},
			{ NAPI.Util.GetHashKey("Jester3"), new VehicleInfo("Luxor Autoroom", 15, 90000)},
			{ NAPI.Util.GetHashKey("Coquette2"), new VehicleInfo("Luxor Autoroom", 15, 105000)},
			{ NAPI.Util.GetHashKey("Gt500"), new VehicleInfo("Luxor Autoroom", 15, 135000)},
			{ NAPI.Util.GetHashKey("Stinger"), new VehicleInfo("Luxor Autoroom", 15, 80000)},
			{ NAPI.Util.GetHashKey("Stingergt"), new VehicleInfo("Luxor Autoroom", 15, 90000)},
			{ NAPI.Util.GetHashKey("Italigtb"), new VehicleInfo("Luxor Autoroom", 15, 155000)},
			{ NAPI.Util.GetHashKey("Windsor2"), new VehicleInfo("Luxor Autoroom", 25, 85000)},
			{ NAPI.Util.GetHashKey("Deviant"), new VehicleInfo("Luxor Autoroom", 15, 160000)},
			{ NAPI.Util.GetHashKey("Dominator3"), new VehicleInfo("Luxor Autoroom", 15, 150000)},
			{ NAPI.Util.GetHashKey("Toros"), new VehicleInfo("Luxor Autoroom", 35, 280000)},
			{ NAPI.Util.GetHashKey("Italigto"), new VehicleInfo("Luxor Autoroom", 15, 290000)},
			{ NAPI.Util.GetHashKey("Jugular"), new VehicleInfo("Luxor Autoroom", 25, 155000)},
			{ NAPI.Util.GetHashKey("Locust"), new VehicleInfo("Luxor Autoroom", 15, 220000)},
			{ NAPI.Util.GetHashKey("Neo"), new VehicleInfo("Luxor Autoroom", 15, 165000)},
			{ NAPI.Util.GetHashKey("Paragon"), new VehicleInfo("Luxor Autoroom", 15, 230000)},
			{ NAPI.Util.GetHashKey("Schlagen"), new VehicleInfo("Luxor Autoroom", 15, 320000)},
			{ NAPI.Util.GetHashKey("Thrax"), new VehicleInfo("Luxor Autoroom", 15, 450000)},
			{ NAPI.Util.GetHashKey("Drafter"), new VehicleInfo("Luxor Autoroom", 15, 208000)},
			{ NAPI.Util.GetHashKey("Emerus"), new VehicleInfo("Luxor Autoroom", 15, 295000)},
			{ NAPI.Util.GetHashKey("Zorrusso"), new VehicleInfo("Luxor Autoroom", 15, 285000)},
			{ NAPI.Util.GetHashKey("Comet5"), new VehicleInfo("Luxor Autoroom", 15, 120000)},
			{ NAPI.Util.GetHashKey("Furia"), new VehicleInfo("Luxor Autoroom", 15, 250000)},
			{ NAPI.Util.GetHashKey("Taipan"), new VehicleInfo("Luxor Autoroom", 15, 240000)},
			{ NAPI.Util.GetHashKey("Entity2"), new VehicleInfo("Luxor Autoroom", 15, 130000)},
			{ NAPI.Util.GetHashKey("Imorgon"), new VehicleInfo("Luxor Autoroom", 15, 125000)},
			{ NAPI.Util.GetHashKey("Flashgt"), new VehicleInfo("Luxor Autoroom", 15, 260000)},
			{ NAPI.Util.GetHashKey("Jb7002"), new VehicleInfo("Luxor Autoroom", 15, 180000)},
			{ NAPI.Util.GetHashKey("Autarch"), new VehicleInfo("Luxor Autoroom", 15, 390000)},
			{ NAPI.Util.GetHashKey("Coquette4"), new VehicleInfo("Luxor Autoroom", 15, 220000)},
			{ NAPI.Util.GetHashKey("Tigon"), new VehicleInfo("Luxor Autoroom", 15, 240000)},
			{ NAPI.Util.GetHashKey("markii"), new VehicleInfo("Luxor Autoroom", 25, 250000, "markii")},

			{ NAPI.Util.GetHashKey("rt3000"), new VehicleInfo("Luxor Autoroom", 15, 110000)},
			{ NAPI.Util.GetHashKey("vectre"), new VehicleInfo("Luxor Autoroom", 15, 115000)},
			{ NAPI.Util.GetHashKey("growler"), new VehicleInfo("Luxor Autoroom", 15, 120000)},
			{ NAPI.Util.GetHashKey("jester4"), new VehicleInfo("Luxor Autoroom", 15, 130000)},
			{ NAPI.Util.GetHashKey("comet6"), new VehicleInfo("Luxor Autoroom", 15, 140000)},


			{ NAPI.Util.GetHashKey("Caddy"), new VehicleInfo("Elite Autoroom", 5, 750000)},
			{ NAPI.Util.GetHashKey("Romero"), new VehicleInfo("Elite Autoroom", 40, 800000)},
			{ NAPI.Util.GetHashKey("Hotknife"), new VehicleInfo("Elite Autoroom", 15, 1250000)},
			{ NAPI.Util.GetHashKey("Ruston"), new VehicleInfo("Elite Autoroom", 15, 1500000)},
			{ NAPI.Util.GetHashKey("Outlaw"), new VehicleInfo("Elite Autoroom", 15, 1750000)},
			{ NAPI.Util.GetHashKey("Stafford"), new VehicleInfo("Elite Autoroom", 30, 2000000)},
			{ NAPI.Util.GetHashKey("Shotaro"), new VehicleInfo("Elite Autoroom", 5, 2500000)},
			{ NAPI.Util.GetHashKey("ZType"), new VehicleInfo("Elite Autoroom", 20, 2500000)},

			{ NAPI.Util.GetHashKey("RRSVR"), new VehicleInfo("Elite Autoroom", 35, 1400000, "Range Rover SVR")},
			{ NAPI.Util.GetHashKey("BmwM3"), new VehicleInfo("Elite Autoroom", 15, 1350000, "BMW M3 E92")},
			{ NAPI.Util.GetHashKey("BmwM5"), new VehicleInfo("Elite Autoroom", 25, 1500000, "BMW M5 F90")},
			{ NAPI.Util.GetHashKey("BmwM8"), new VehicleInfo("Elite Autoroom", 15, 1575000, "BMW M8 F92")},
			{ NAPI.Util.GetHashKey("MBC63S"), new VehicleInfo("Elite Autoroom", 15, 1450000, "Mercedes C63S")},
			{ NAPI.Util.GetHashKey("MBG63"), new VehicleInfo("Elite Autoroom", 35, 1600000, "Mercedes G63")},
			{ NAPI.Util.GetHashKey("AudiR8"), new VehicleInfo("Elite Autoroom", 15, 1585000, "Audi R8")},
			{ NAPI.Util.GetHashKey("BmwI8"), new VehicleInfo("Elite Autoroom", 15, 1550000, "BMW i8")},
			{ NAPI.Util.GetHashKey("DodgeViper"), new VehicleInfo("Elite Autoroom", 15, 1475000, "Dodge Viper")},
			{ NAPI.Util.GetHashKey("BentleyC"), new VehicleInfo("Elite Autoroom", 25, 1500000, "Bentley Continental")},
			{ NAPI.Util.GetHashKey("Camry"), new VehicleInfo("Elite Autoroom", 25, 500000, "Toyota Camry")},
			{ NAPI.Util.GetHashKey("LX570"), new VehicleInfo("Elite Autoroom", 35, 800000, "Lexus LX570")},
			{ NAPI.Util.GetHashKey("AudiRS7"), new VehicleInfo("Elite Autoroom", 25, 1000000, "Audi RS7")},
			{ NAPI.Util.GetHashKey("NGTR"), new VehicleInfo("Elite Autoroom", 15, 1600000, "Nissan GTR")},
			{ NAPI.Util.GetHashKey("Lambo770"), new VehicleInfo("Elite Autoroom", 15, 3000000, "Lamborghini Centenario")},
			{ NAPI.Util.GetHashKey("BMWE38"), new VehicleInfo("Elite Autoroom", 25, 400000, "BMW E38")},
			{ NAPI.Util.GetHashKey("MBE420"), new VehicleInfo("Elite Autoroom", 25, 400000, "Mercedes E420")},
			{ NAPI.Util.GetHashKey("BentleyB"), new VehicleInfo("Elite Autoroom", 35, 1500000, "Bentley Bentayga")},
			{ NAPI.Util.GetHashKey("MazdaRX7"), new VehicleInfo("Elite Autoroom", 15, 250000, "Mazda RX7")},
			{ NAPI.Util.GetHashKey("Supra"), new VehicleInfo("Elite Autoroom", 15, 1100000, "Toyota Supra")},
			{ NAPI.Util.GetHashKey("SubaruWRX"), new VehicleInfo("Elite Autoroom", 25, 700000, "Subaru WRX")},
			{ NAPI.Util.GetHashKey("BMWX6"), new VehicleInfo("Elite Autoroom", 35, 1600000, "BMW X6M")},
			{ NAPI.Util.GetHashKey("MBC63"), new VehicleInfo("Elite Autoroom", 25, 1700000, "Mercedes C63")},
			{ NAPI.Util.GetHashKey("MLEvoX"), new VehicleInfo("Elite Autoroom", 25, 650000, "Mitsubishi Lancer EVO X")},
			{ NAPI.Util.GetHashKey("AudiTT"), new VehicleInfo("Elite Autoroom", 15, 1400000, "Audi TT")},
			{ NAPI.Util.GetHashKey("Skyline"), new VehicleInfo("Elite Autoroom", 25, 1000000, "Nissan Skyline")},
			{ NAPI.Util.GetHashKey("TeslaS"), new VehicleInfo("Elite Autoroom", 35, 2000000, "Tesla Model S")},
			{ NAPI.Util.GetHashKey("Regera"), new VehicleInfo("Elite Autoroom", 15, 1500000, "Koenigsegg Regera")},
			{ NAPI.Util.GetHashKey("Lambo640"), new VehicleInfo("Elite Autoroom", 15, 2000000, "Lamborghini Murcielago")},
			{ NAPI.Util.GetHashKey("Ferrari488"), new VehicleInfo("Elite Autoroom", 15, 1650000, "Ferrari 488")},
			{ NAPI.Util.GetHashKey("quad1"), new VehicleInfo("Elite Autoroom", 15, 0, "Ferrari 488")},
			{ NAPI.Util.GetHashKey("mbamggt"), new VehicleInfo("Elite Autoroom", 15, 1800000, "mbamggt")},
			{ NAPI.Util.GetHashKey("audia6"), new VehicleInfo("Elite Autoroom", 25, 1100000, "audia6")},
			{ NAPI.Util.GetHashKey("porschegt4"), new VehicleInfo("Elite Autoroom", 15, 1500000, "Porsche GT 4")},
			{ NAPI.Util.GetHashKey("cadctsv"), new VehicleInfo("Elite Autoroom", 25, 850000, "Cadillac CTS V")},
			{ NAPI.Util.GetHashKey("Prototipo"), new VehicleInfo("Exotic DonateRoom", 25, 2500000, "Prototipo")},
			{ NAPI.Util.GetHashKey("Tezeract"), new VehicleInfo("Exotic DonateRoom", 25, 2250000, "Tezeract")},
			{ NAPI.Util.GetHashKey("Tyrant"), new VehicleInfo("Exotic DonateRoom", 25, 2250000, "Tyrant")},
			{ NAPI.Util.GetHashKey("Openwheel2"), new VehicleInfo("Exotic DonateRoom", 10, 1500000, "Openwheel2")},
			{ NAPI.Util.GetHashKey("Nero2"), new VehicleInfo("Exotic DonateRoom", 25, 600000, "Nero2")},
			{ NAPI.Util.GetHashKey("Camper"), new VehicleInfo("Exotic DonateRoom", 45, 500000, "Camper")},
			{ NAPI.Util.GetHashKey("Patriot2"), new VehicleInfo("Exotic DonateRoom", 25, 400000, "Patriot2")},
			{ NAPI.Util.GetHashKey("Speedo2"), new VehicleInfo("Exotic DonateRoom", 25, 400000, "Speedo2")},
			{ NAPI.Util.GetHashKey("Journey"), new VehicleInfo("Exotic DonateRoom", 25, 350000, "Journey")},
			{ NAPI.Util.GetHashKey("Vagrant"), new VehicleInfo("Exotic DonateRoom", 5, 1000000, "Journey")},
			{ NAPI.Util.GetHashKey("Veto"), new VehicleInfo("Exotic DonateRoom", 25, 250000, "Veto")},
			{ NAPI.Util.GetHashKey("Italirsx"), new VehicleInfo("Luxor Autoroom", 25, 950000, "Italirsx")},
			{ NAPI.Util.GetHashKey("Btype3"), new VehicleInfo("Elite Autoroom", 25, 2250000, "Btype3")},
			{ NAPI.Util.GetHashKey("Fudocycle"), new VehicleInfo("Elite Autoroom", 5, 850000, "Fudocycle")},
			{ NAPI.Util.GetHashKey("Deathbike2"), new VehicleInfo("Elite Autoroom", 5, 700000, "Deathbike2")},
			{ NAPI.Util.GetHashKey("Deathbike3"), new VehicleInfo("Elite Autoroom", 5, 700000, "Deathbike3")},
			{ NAPI.Util.GetHashKey("Lambo580"), new VehicleInfo("Elite Autoroom", 15, 2750000, "Lambo580")},
			{ NAPI.Util.GetHashKey("Db11"), new VehicleInfo("Elite Autoroom", 25, 1500000, "Db11")},
			{ NAPI.Util.GetHashKey("jesko"), new VehicleInfo("Elite Autoroom", 15, 7500000, "jesko")},
			{ NAPI.Util.GetHashKey("vapidse"), new VehicleInfo("Elite Autoroom", 70, 1500000, "vapidse")},
			{ NAPI.Util.GetHashKey("minic"), new VehicleInfo("Elite Autoroom", 20, 500000, "minic")},
			{ NAPI.Util.GetHashKey("mbx18"), new VehicleInfo("Elite Autoroom", 45, 1700000, "mbx18")},
			{ NAPI.Util.GetHashKey("bmwx5"), new VehicleInfo("Elite Autoroom", 35, 1400000, "bmwx5")},
			{ NAPI.Util.GetHashKey("impala67"), new VehicleInfo("Elite Autoroom", 25, 700000, "impala67")},
			{ NAPI.Util.GetHashKey("jeepsrt8"), new VehicleInfo("Elite Autoroom", 35, 400000, "jeepsrt8")},
			{ NAPI.Util.GetHashKey("sian"), new VehicleInfo("Elite Autoroom", 15, 8000000, "sian")},
			{ NAPI.Util.GetHashKey("escalade900"), new VehicleInfo("Elite Autoroom", 35, 1000000, "escalade900")},
			{ NAPI.Util.GetHashKey("lc100"), new VehicleInfo("Elite Autoroom", 35, 500000, "lc100")},
			{ NAPI.Util.GetHashKey("mb63gls"), new VehicleInfo("Elite Autoroom", 35, 1700000, "mb63gls")},
			{ NAPI.Util.GetHashKey("niva"), new VehicleInfo("Elite Autoroom", 20, 285000, "niva")},
			{ NAPI.Util.GetHashKey("panamera"), new VehicleInfo("Elite Autoroom", 25, 1850000, "panamera")},
			{ NAPI.Util.GetHashKey("urus"), new VehicleInfo("Elite Autoroom", 35, 2040000, "urus")},
			{ NAPI.Util.GetHashKey("silvias15"), new VehicleInfo("Elite Autoroom", 20, 700000, "silvias15")},
			{ NAPI.Util.GetHashKey("rrcullinan"), new VehicleInfo("Elite Autoroom", 30, 700000, "rrcullinan")},
			{ NAPI.Util.GetHashKey("diabloSV"), new VehicleInfo("Elite Autoroom", 15, 700000, "diabloSV")},
			{ NAPI.Util.GetHashKey("lexusgsf"), new VehicleInfo("Elite Autoroom", 20, 700000, "lexusgsf")},
			{ NAPI.Util.GetHashKey("p1"), new VehicleInfo("Elite Autoroom", 20, 700000, "p1")},
			{ NAPI.Util.GetHashKey("fxxkevo"), new VehicleInfo("Elite Autoroom", 20, 700000, "fxxkevo")},
			{ NAPI.Util.GetHashKey("taycan"), new VehicleInfo("Elite Autoroom", 20, 700000, "taycan")},
			{ NAPI.Util.GetHashKey("lp700r"), new VehicleInfo("Exotic Autoroom", 20, 700000, "lp700r")},
			{ NAPI.Util.GetHashKey("g636x6"), new VehicleInfo("Exotic Autoroom", 90, 700000, "g636x6")},
			{ NAPI.Util.GetHashKey("apriora"), new VehicleInfo("Exotic Autoroom", 20, 700000, "apriora")},
			{ NAPI.Util.GetHashKey("ecto1"), new VehicleInfo("Exotic Autoroom", 20, 700000, "ecto1")},
			//
			{ NAPI.Util.GetHashKey("astron"), new VehicleInfo("Elite Autoroom", 25, 700000, "Pfister Astron")},
			{ NAPI.Util.GetHashKey("baller7"), new VehicleInfo("Elite Autoroom", 35, 700000, "Gallivanter Baller ST")},
			{ NAPI.Util.GetHashKey("buffalo4"), new VehicleInfo("Elite Autoroom", 15, 700000, "Bravado Buffalo STX")},
			{ NAPI.Util.GetHashKey("champion"), new VehicleInfo("Elite Autoroom", 15, 700000, "Dewbauchee Champion")},
			{ NAPI.Util.GetHashKey("cinquemila"), new VehicleInfo("Elite Autoroom", 25, 700000, "Lampadati Cinquemila")},
			{ NAPI.Util.GetHashKey("comet7"), new VehicleInfo("Elite Autoroom", 5, 700000, "Pfister Comet S2 Cabrio")},
			{ NAPI.Util.GetHashKey("deity"), new VehicleInfo("Elite Autoroom", 15, 700000, "Enus Deity")},
			{ NAPI.Util.GetHashKey("granger2"), new VehicleInfo("Elite Autoroom", 35, 700000, "Declasse Granger 3600LX")},
			{ NAPI.Util.GetHashKey("ignus"), new VehicleInfo("Elite Autoroom", 25, 700000, "Pegassi Ignus")},
			{ NAPI.Util.GetHashKey("iwagen"), new VehicleInfo("Elite Autoroom", 25, 700000, "Obey I-Wagen")},
			{ NAPI.Util.GetHashKey("jubilee"), new VehicleInfo("Elite Autoroom", 35, 700000, "Enus Jubilee")},
			{ NAPI.Util.GetHashKey("mule5"), new VehicleInfo("Elite Autoroom", 20, 700000, "Maibatsu Mule")},
			{ NAPI.Util.GetHashKey("patriot3"), new VehicleInfo("Elite Autoroom", 35, 700000, "Mammoth Patriot Mil-Spec")},
			{ NAPI.Util.GetHashKey("reever"), new VehicleInfo("Elite Autoroom", 5, 700000, "Western Reever")},
			{ NAPI.Util.GetHashKey("shinobi"), new VehicleInfo("Elite Autoroom", 5, 700000, "Nagasaki Shinobi")},
			{ NAPI.Util.GetHashKey("youga4"), new VehicleInfo("Elite Autoroom", 20, 700000, "Vapid Youga Custom")},
			{ NAPI.Util.GetHashKey("zeno"), new VehicleInfo("Elite Autoroom", 5, 700000, "Overflod Zeno")},
			{ NAPI.Util.GetHashKey("gemera"), new VehicleInfo("Elite Autoroom", 10, 700000, "gemera")},
			{ NAPI.Util.GetHashKey("bvit"), new VehicleInfo("Elite Autoroom", 10, 700000, "bvit")},
			{ NAPI.Util.GetHashKey("16challenger"), new VehicleInfo("Elite Autoroom", 22, 700000, "16challenger")},
			{ NAPI.Util.GetHashKey("w223"), new VehicleInfo("Elite Autoroom", 25, 700000, "w223")},
			{ NAPI.Util.GetHashKey("c7"), new VehicleInfo("Elite Autoroom", 15, 700000, "c7")},
			{ NAPI.Util.GetHashKey("corsita"), new VehicleInfo("Premium Autoroom", 15, 145000, "c7")},
			{ NAPI.Util.GetHashKey("greenwood"), new VehicleInfo("Low Autoroom", 15, 45000, "c7")},
			{ NAPI.Util.GetHashKey("lm87"), new VehicleInfo("Luxor Autoroom", 15, 100000, "lm87")},
			{ NAPI.Util.GetHashKey("torero2"), new VehicleInfo("Luxor Autoroom", 15, 700000, "torero2")},
			{ NAPI.Util.GetHashKey("omnisegt"), new VehicleInfo("Premium Autoroom", 15, 700000, "omnisegt")},
			{ NAPI.Util.GetHashKey("sm722"), new VehicleInfo("Luxor Autoroom", 15, 540000, "sm722")},
			{ NAPI.Util.GetHashKey("c8"), new VehicleInfo("Luxor Autoroom", 10, 700000, "c8")},
			{ NAPI.Util.GetHashKey("brz13"), new VehicleInfo("Premium Autoroom", 15, 700000, "brz13")},
			{ NAPI.Util.GetHashKey("zagatosb"), new VehicleInfo("Luxor Autoroom", 20, 540000, "zagatosb")},
            { NAPI.Util.GetHashKey("ftype"), new VehicleInfo("Elite Autoroom", 20, 540000, "ftype")},
            { NAPI.Util.GetHashKey("m750li"), new VehicleInfo("Elite Autoroom", 20, 540000, "m750li")},
            { NAPI.Util.GetHashKey("monza"), new VehicleInfo("Elite Autoroom", 20, 540000, "monza")},
            { NAPI.Util.GetHashKey("mysterycar"), new VehicleInfo("Elite Autoroom", 20, 540000, "mysterycar")},



        };

        public static int GetMaxSlots(uint Model)
        {
			try
			{
				if (VehicleData.ContainsKey(Model)) return VehicleData[Model].MaxSlots;
				return Repository.InventoryMaxSlots["vehicle"];
			}
			catch (Exception e)
			{
				Log.Write($"GetMaxSlots Exception: {e.ToString()}");
				return 15;
			}
        }
		public static string GetName(uint Model)
		{
			try
			{
				if (VehicleData.ContainsKey(Model)) return VehicleData[Model].Name;
				return null;
			}
			catch (Exception e)
			{
				Log.Write($"GetName Exception: {e.ToString()}");
				return null;
			}
		}
	}
}
